openfisca/openfisca-core

openfisca_core/columns.py

Stop requesting `0` padding in front of months and days numbers.
This makes it in particular easier to interact with the Web API from vanilla JS, as there is no native method to pad numbers.

Improve dates parsing resilience

---

openfisca_core/reforms.py

@cbenz,
I had a bug when trying to call two reforms at the same times. I think `build_reform` takes only one argument, while in `compose_reforms_reducer` two were provided. 
I did a quick and dirty fix for my own needs, but there is probably other stuff to do to keep it clean. 
Thanks !

Bug fix: build_reform now takes only one argument

---

openfisca_core/periods.py

Introduce some reference periods in openfisca_core/periods.py in order to simplify period uses in formula.
Eg : 
Before : 
```python
period = period.start.offset('first-of', 'month').period('month')
two_years_ago = period.start.offset('first-of', 'year').period('year').offset(-2)
last_month = period.start.period('month').offset(-1)
```
After :
```python
period = period.this_month
two_years_ago = period.n_2
last_month = period.last_month
```

Introduce reference periods

---

openfisca_core/formulas.py

To be able to replace [cryptic lines](https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/prestations/education.py#L52) such as :
```python
nb_enfants_college = zeros(len(rfr))
```
by 
```python
nb_enfants_college = 0
```
If a function returns a scalar, it will be automatically be turned into a numpy array of the right size.

Allow SimpleFormula function to return a scalar number

---

openfisca_core/columns.py
openfisca_core/formulas.py
openfisca_core/reforms.py
openfisca_core/scripts/measure_performances.py
openfisca_core/tests/dummy_country.py
openfisca_core/tests/test_countries.py

Connected to #355 
Follows #364 
I didn't deprecate `reference_input_variable`, so probably no migration needed on other repositories right now.

Uniformize variable declaration

---

openfisca_core/legislationsxml.py

We need to be able to inject parameters from a separate xml file at the root level. I fixed it with this commit: if you let the path to `None`, it will put the params under root. Feel free to suggest another implementation ;)

Allow insertion of parameters at the root level

---

openfisca_core/base_functions.py
openfisca_core/columns.py
openfisca_core/formulas.py

Introduces a new base function requested_period_last_or_next_value, similar to requested_period_last_value except it can take a value from the future is there is none in the past.
Exemple : 
Input : `alt = True` for a child on 2016-01
If I request `alt`in 2015-12, I will get True.
It is helpful for calculating values in the past more accurately, which is useful for ppa_fictive calculations.
Depends on https://github.com/openfisca/openfisca-france/pull/427
Depends on https://github.com/openfisca/openfisca-parsers/pull/10

Add base function requested_period_last_or_next_value

---

openfisca_core/formulas.py

The result size must be the target entity'one, not necessarily the calling formula.

Fix sum_by_entity

---

CHANGELOG.md
openfisca_core/holders.py
openfisca_core/scenarios.py
openfisca_core/simulations.py
openfisca_core/taxbenefitsystems.py
openfisca_core/tests/test_opt_out_cache.py
setup.py

When using it for a large population, having too many variables in cache make openfisca performances drop.
This introduces a mechanism that enables some variables not to be cached.
The names of the variables we don't want to cache must passed to the tax benefit system in a set : 
```python
tax_benefit_system.cache_blacklist = set(['intermediate'])
```
Then an extra parameter must be given when creating the simulation to activate this behaviour:
```python
simulation = scenario.new_simulation(debug = True, opt_out_cache = True)
```
See the [test file](https://github.com/openfisca/openfisca-core/blob/cache_opt_out/openfisca_core/tests/test_opt_out_cache.py) for a full exemple.
@cbenz @eraviart @laem @benjello any feedback ? Is naming clear enough ?

Implement mechanism to opt out of cache for some variables

---

CHANGELOG.md
openfisca_core/taxbenefitsystems.py
setup.py

Enables this usage:
```py
tax_benefit_system.load_extension('openfisca_paris')
```
Provided that `openfisca_paris` has been installed via pip before. This is useful to define the extensions to load via the api config file. See https://github.com/openfisca/openfisca-web-api/pull/61.

Load extensions from pip packages

---

CHANGELOG.md
openfisca_core/simulations.py
openfisca_core/tests/test_simulations.py
setup.py

Especially from notebooks:
```python
scenario = tax_benefit_system.new_scenario().init_single_entity(
parent1=dict(salaire_de_base=25000),
period=2014,
)
simulation = scenario.new_simulation(trace=True)
simulation.calculate('irpp', 2014, print_trace=True)
```
Outputs:
```
irpp@foyers_fiscaux<2014>[-1193.05]
|---> iai@foyers_fiscaux<2014>[1193.05]
|     |---> iaidrdi@foyers_fiscaux<2014>[1193.05]
|     |     |---> ip_net@foyers_fiscaux<2014>[1193.05]
|     |     |---> reductions@foyers_fiscaux<2014>[0.0]
|     |---> plus_values@foyers_fiscaux<2014>[0.0]
|     |     |---> f3vg@foyers_fiscaux<2014>[0]
|     |     |---> f3vh@foyers_fiscaux<2014>[0]
|     |     |---> f3vl@foyers_fiscaux<2014>[0]
|     |     |---> f3vm@foyers_fiscaux<2014>[0]
|     |     |---> f3vi@individus<2014>[0]
|     | …
```

Implement printing trace tree from Python

---

CHANGELOG.md
openfisca_core/entities.py
openfisca_core/tests/test_scenarios.py
setup.py

* Fixup 4.1.2:
* When building positions, handle cases where persons belonging to an entity are not grouped by entity in the persons array.

Fixup #421

---

travis-run-tests.sh

When only the README (or any other file that is not _in_ the package) is modified, don't force a version update.

Loosen versionning enforcing

---

CHANGELOG.md
openfisca_core/formulas.py
setup.py

The `new_filled_column` function takes several kwargs.
Some of them – `set_input`, `calculate_output` and `default` are not handled correctly.
This is a fix for this problem.

Fix some new_filled_column kwargs

---

CHANGELOG.md
openfisca_core/holders.py
openfisca_core/tests/test_extra_params.py
setup.py

There is a bug when computing intermediate variables with the API.
`DatedVariables.to_value_json ` method was not compatible with extra parameter.

Fix to_json for dated variables with extra params

---

CHANGELOG.md
openfisca_core/taxscales.py
openfisca_core/tests/test_tax_scales.py
setup.py

Fix occasionnal `NaN` creation in `MarginalRateTaxScale.calc`

---

CHANGELOG.md
openfisca_core/legislations.py
setup.py

This bug was noticed working on senegal.
Connected to openfisca/openfisca-web-api#76.
Replaces #436

Handle case when CompactNode.name is None

---

CHANGELOG.md
openfisca_core/scripts/__init__.py
openfisca_core/scripts/run_test.py
openfisca_core/tools/__init__.py
setup.py

* Improve `openfisca-run-test` script
- Make country package detection more robust (it only worked for packages installed in editable mode)
- Use spaces instead of commas as separator in the script arguments when loading several extensions or reforms (this is more standard)
* Refactor the `scripts` module to seperate the logic specific to yaml test running from the one that can be re-used by any script which needs to build a tax and benefit system.

Improve test runner

---

CHANGELOG.md
openfisca_core/model_api.py
openfisca_core/taxbenefitsystems.py
setup.py

* Move `base.py` content (file usually located in country packages) to core module `formula_toolbox` so that it can be reused by all countries
* Use `AbstractScenario` if no custom scenario is defined for a tax and benefit sytem
See impact on https://github.com/openfisca/openfisca-france/pull/697

Simplify boilerplate

---

CHANGELOG.md
doc/requirements.txt
openfisca_core/formulas.py
openfisca_core/taxbenefitsystems.py
setup.py
tests/test_reforms.py

Connected to openfisca/openfisca-doc#43
I tried something new as an experiment: deprecating without removing a function.
My motivation is to avoid the fixed cost of publishing a major (updating all the dependencies) for something small where retro-compatibility is easy to implement.
The workflow I imagine would be wait for the next major bumps to remove it for good. Either we:
- Remove it in the next PR that brings a major bump. Doesn't respect the one PR = one goal principle.
- Publish the next major bump as a pre-release. Then all deprecated stuff can be removed right after.
To be discussed later with @MattiSG @cbenz, this is not a priority.

Document neutralize_variable

---

doc/requirements.txt

It seems that we need to explicit the minimal version we want. Otherwise and old cached version is used by readthedocs.

Upgrade ref doc requirements

---

CHANGELOG.md
openfisca_core/scripts/run_test.py
openfisca_core/tools/test_runner.py
setup.py
tests/core/test_countries.py
tests/core/test_yaml.py

Connected to openfisca/openfisca-france#734
* Use `nose` in the `openfisca-run-test` script
- This avoids boilerplate code on country packages, and makes parallelism easier to set on Circle CI.

Handle parallel testing

---

CHANGELOG.md
setup.py

Require numpy < 1.13

---

CHANGELOG.md
openfisca_core/scripts/__init__.py
openfisca_core/taxbenefitsystems.py
openfisca_web_api_preview/loader/tax_benefit_system.py
setup.py
tests/core/test_extensions.py

Connected to #464 
- Add stack trace when a module import fails at `openfisca-run-test`
- Improve error message whether import is called with `-c` option or not

Do not hide error at module import failure

---

CHANGELOG.md
openfisca_core/base_functions.py
openfisca_core/formulas.py
openfisca_core/model_api.py
setup.py

This `base_function` was hidden in `openfisca_core/formulas.py` instead of `openfisca_core/base_functions.py`.
Therefore several changes applied to base functions were not applied to it. This PR fixes it, and make this base function work [like the others](https://github.com/openfisca/openfisca-core/blob/master/openfisca_core/base_functions.py#L11)
This bug was without consequences, as this base function is rarely used. We however need to fix that to keep migrating france code towards the `v4` syntax.

Make missing_value base function compatible with v4 syntax and extra params

---

CHANGELOG.md
setup.py

Connected to #500 
* Deprecate `parsers`
- They can no longer be installed through `pip install openfisca_core[parsers]`
- They can still install them directly with `pip install openfisca_parsers`, but they won't be maintained.

Deprecate parsers

---

CHANGELOG.md
openfisca_core/entities.py
openfisca_core/enumerations.py
openfisca_web_api_preview/app.py
openfisca_web_api_preview/loader/spec.py
openfisca_web_api_preview/loader/variables.py
setup.py
tests/web_api/test_calculate.py
tests/web_api/test_variables.py

Connected to openfisca/legislation-explorer#95
Depends on https://github.com/openfisca/country-template/pull/16
In the preview web API, for variables of type `Enum`:
* Accept and recommand to use strings as simulation inputs, instead of the enum indices.
- For instance, `{"housing_occupancy_status": {"2017-01": "Tenant"}}` is now accepted and prefered to `{"housing_occupancy_status": {"2017-01": 0}}`).
- Using the enum indices as inputs is _still accepted_ for backward compatibility, but _should not_ be encouraged.
* Return strings instead of enum indices.
- For instance, is `housing_occupancy_status` is calculated for `2017-01`, `{"housing_occupancy_status": {"2017-01": "Tenant"}}` is now returned, instead of `{"housing_occupancy_status": {"2017-01": 0}}`.
* In the …

Add Enum possible values to the web API

---

CHANGELOG.md
openfisca_core/legislation.xsd
setup.py
tests/core/parameter_validation/references.xml
tests/core/parameter_validation/test_parameter_validation.py

- Add support for `reference` attributes on all parameter node types.
- Allows for https://github.com/openfisca/openfisca-france/pull/789 to be merged.
Fix #557.

Support reference attributes on all parameter node types

---

CHANGELOG.md
openfisca_core/variables.py
setup.py

Fixes #556 
- Allows for user to put a coma at the end of a variable reference, without consequence to the API output.
- All variable references are transformed into lists of strings.

Check type reference

---

CHANGELOG.md
openfisca_core/entities.py
setup.py

Connected to openfisca/country-template#19
- Introduce `doc` attribute on `entities`
- Allows for documentation definition on every entity instance. Default value set to empty string.

Document entities

---

Makefile
README.md
deploy-if-version-bump.sh

Connected to #577 
- Stop deployment on `api-test.openfisca.fr`.
- The functionality is now provided by `fr.openfisca.org`

Clean references to old api

---

CHANGELOG.md
README.md
openfisca_web_api_preview/app.py
setup.py

Connected to openfisca/openfisca-france#821
- By adding your Piwik AUTH token to the gunicorn environment variable when serving the API, you can track your API visitor's by IP on Piwik

Track IPs from API visitors

---

CHANGELOG.md
openfisca_web_api_preview/openAPI.yml
setup.py

Connected to openfisca/openfisca-core#577
Technical change : Add a link in the openAPI documentation to the OpenFisca documentation page explaining the web API inputs and outputs for the `calculate`route.

Add access to documentation of the web API inputs and outputs

---

CHANGELOG.md
openfisca_core/parameters.py
openfisca_core/periods.py
openfisca_core/taxbenefitsystems.py
openfisca_core/taxscales.py
openfisca_core/tools/__init__.py
openfisca_web_api_preview/loader/parameters.py
setup.py
tests/core/parameter_validation/test_parameter_validation.py
tests/core/test_parameters.py
tests/web_api/test_helpers.py

Depends on https://github.com/openfisca/country-template/pull/23
While working on #573  , I did a few changes to fix some bugs and make navigating the legislation more pleasant. I didn't include it in #575 to stay focused, but here they are 🙂 .
- Improve the representations of parameters when navigating the legislation in Python.
For instance:
```
tax_benefit_system.parameters.benefits
>>> basic_income:
>>>   2015-12-01: 600.0
>>> housing_allowance:
>>>   2016-12-01: None
>>>   2010-01-01: 0.25
```
- Be more flexible about parameters definitions
The two following expressions are for instance striclty equivalent:
```
Parameter("taux", {"2015-01-01": 2000})
Parameter("taux", {"values": {"2015-01-01":{"value": 2000}}})
```
- Request parameter at a given date with the …

Improve parameters navigating

---

CHANGELOG.md
Makefile
README.md
doc/source/index.rst
doc/source/openfisca_serve.rst
openfisca_core/parameters.py
openfisca_core/scripts/__init__.py
openfisca_core/scripts/openfisca_command.py
openfisca_core/scripts/run_test.py
openfisca_web_api_preview/app.py
openfisca_web_api_preview/loader/__init__.py
openfisca_web_api_preview/scripts/serve.py
openfisca_web_api_preview/scripts/server_configuration.py
setup.py
tests/web_api/__init__.py
tests/web_api/test_extensions.py

Connected to #576 
- Introduce `openfisca-serve` for new API
- Allows for serving OpenFisca extensions with `-e` option. Example: openfisca-serve -c openfisca_country_template -e openfisca_extension_template

Serve extensions in the API

---

openfisca_core/parameters.py
tests/core/parameters_fancy_indexing/test_fancy_indexing.py

This is a slight improvement of #589 to be able to use the newly introduced enums when requesting a parameter dynamically depending on a variable.
See test for example.

Enable fancy indexing on enum variables

---

CHANGELOG.md
openfisca_core/holders.py
setup.py
tests/core/test_holders.py

- Allow string arrays as inputs for Enum variables
For instance, following the example from 21.0.0, the following now works:
```py
holder = household.get_holder('housing_occupancy_status')
holder.set_input(period, np.asarray(['owner']))
```

Allow string arrays as inputs for Enum variables

---

CHANGELOG.md
openfisca_core/base_functions.py
openfisca_core/data_storage.py
openfisca_core/holders.py
openfisca_core/memory_config.py
openfisca_core/periods.py
openfisca_core/simulations.py
openfisca_core/variables.py
setup.py
tests/core/test_base_functions.py
tests/core/test_extra_params.py
tests/core/test_holders.py
tests/core/test_opt_out_cache.py
tests/core/test_reforms.py

Depends on #598.
_Attention: this PR is opened towards `update-taxipp-v20` to make the diff clearer. Once #598 is merged, the target branch must be changed to master_
- Improve [`holder.get_memory_usage`]((http://openfisca.readthedocs.io/en/latest/holder.html#openfisca_core.holders.Holder.get_memory_usage)):
- Add `nb_requests` and `nb_requests_by_array` fields in the memory usage stats for traced simulations.
- Enable intermediate data storage on disk to avoid memory overflow
- Introduce `memory_config` option in `Simulation` constructor
- This allows fine tuning of memory management in OpenFisca
For instance:
```
from openfisca_core.memory_config import MemoryConfig
config = MemoryConfig(
max_memory_occupation = 0.95,  # When 95% of the virtual memory is full, switch to disk storage …
```

Handle memory overflows

---

CHANGELOG.md
openfisca_core/data_storage.py
openfisca_core/formulas.py
setup.py
tests/core/test_holders.py

- Fix two bugs that appeared with 21.2.0:
- Properly encode the result of a formula returning an Enum value
- Enable storing an Enum value on disk

Properly encode the result of formulas returning an enum

---

CHANGELOG.md
openfisca_core/taxbenefitsystems.py
setup.py

- When a variable file is loaded twice in the same python interpreter, make sure the second loading doesn't corrupt the first one.
- This fixes a bug introduced in 21.0.2, which could lead to a corruption of the tax and benefit in rare edge cases

Insulate TBS

---

CHANGELOG.md
openfisca_core/scripts/run_test.py
openfisca_core/tools/test_runner.py
setup.py

- Introduce new options `--only` and '--ignore` to openfisca-run-test
- Allows for filter tthe variables to test in YAML tests

Add run test options

---

CHANGELOG.md
openfisca_core/decompositions.py
setup.py

- Hack to handle a computing error with decompositions

Switch to calculate_add when claculate_output doesn't work

---

CHANGELOG.md
doc/source/index.rst
doc/source/simulation_generator.rst
openfisca_core/scripts/simulation_generator.py
setup.py
tests/core/simulation_generator.py

Introduce a helper function to generate arbitrarily big populations. 
I used it a lot to investigate performances, and it could be reused. I put in in tests, but there may be a better spot.
This is clearly low priority

Introduce simulation generators

---

CHANGELOG.md
openfisca_core/entities.py
setup.py
tests/core/test_entities.py

Connected to openfisca/openfisca-core#586
Si https://github.com/openfisca/openfisca-core/pull/602 est mergée avant, un rebase attentif sera nécessaire
- Introduce:
- [`person.get_rank(entity, criteria, condition)`](https://github.com/openfisca/openfisca-core/blob/migrate-cmu/openfisca_core/entities.py#L279-L294)
- [`entity.value_kth_person(k, array, default)`](https://github.com/openfisca/openfisca-core/blob/migrate-cmu/openfisca_core/entities.py#L516-L521)

Introduce new entities helper

---

CHANGELOG.md
openfisca_core/entities.py
setup.py
tests/core/test_entities.py

- Improve entities projection consistency
Before, there were inconsistencies in the behaviors of projectors:
_For instance, for a simulation that contains 4 persons in 1 household:_
```py
person.household('rent')  # The rent paid by the household of the person.
>>> [800, 800, 800, 800]  # Has the dimension of persons (4)
salaries = person.household.members('salary')
sum_salary = person.houdehold.sum(salaries)  # The sum of the salaries of the person's family
>>> [4000] Has the dimension of household (1)
```
Now, consistency have been enforced for all entities related helpers (`sum`, `min`, `max`, `all`, `any`, `has_role`, etc.)
```py
person.household('rent')  # The rent paid by the household of the person.
>>> [800, 800, 800, 800]  # Has the dimension of persons (4)
salaries = …
```

Improve projectors

---

CHANGELOG.md
openfisca_core/parameters.py
setup.py
tests/core/test_parameters.py

- Make sure `ParameterNode:repr` generates a valid YAML representation

Make sure ParameterNode:repr generates a valid YAML representation

---

CHANGELOG.md
openfisca_core/parameters.py
setup.py

On `france`:
-  `nosetests tests/test_basics.py` drops from `35s` to `25s`
-  [This file](https://github.com/openfisca/tutorial/blob/master/python/scripts/generate_situation_examples/try_situation_examples.py) drops from `5.26s` to `3.55s`
Interesting lessons:
- Performances waste does not necessarily happen where you think it does
- Flexibles user-friendly interfaces can ruin performances if called under the hood

Improve parameters performances

---

CHANGELOG.md
openfisca_core/entities.py
openfisca_core/variables.py
setup.py
tests/core/test_entities.py

* Fix `entity.max`, `entity.min`, `entity.all` and `entity.reduce` for multi-entities simulations.
- This issue was not affecting simulations with several persons in a _single_ entity
- These operators were not working as expected in case the persons of the simulation were not sorted by entity id in the persons vector. For instance:
- First household: [Alice, Bob]
- Second household: [Cesar]
- Persons vector: [Alice, Cesar, Bob]

Fix some entity operators for multi-entities simulations.

---

README.md

Fixes #622 
In order to run a single test file or a single test definition, `nose`
expects you to pass the path relative to its working directory.
For example if your `setup.cfg` looks like this:
[nosetests]
where = tests
Then to run your tests you should do:
> find . -name test_parameters.py
./tests/core/test_parameters.py
./tests/web_api/basic_case/test_parameters.py
> nosetests core/test_parameters.py
Ran 9 tests in 0.007s
nosetests core/test_parameters.py:test_parameter_for_period
Ran 1 test in 0.000s
See: https://nose.readthedocs.io/en/latest/usage.html#selecting-testsDocument

Document how to run a specific test with nosetests

---

.circleci/config.yml

* Cache known hosts after checkout in CircleCI
* Details:
- Otherwise it fails to push tags
- See https://discuss.circleci.com/t/git-clone-fails-in-circle-2-0/15211

Cache known hosts after checkout

---

CHANGELOG.md
openfisca_core/indexed_enums.py
openfisca_core/variables.py
setup.py
tests/core/test_holders.py

Fixes #652 
* Fix `dtype` attribute for `EnumArray`s (returned when calculating a variable of `value_type` `Enum`):
- It was the type `np.int16` and not the dtype instance `np.dtype(np.int16)`
- This caused issue when trying to export an `EnumArray` with `pandas`

Fix enum dtype

---

CHANGELOG.md
openfisca_core/taxbenefitsystems.py
setup.py

Fixes #642 
* Allow two variable file to have the same name in a tax and benefit system
- A [collision](https://github.com/openfisca/openfisca-core/issues/642) between module names made it impossible so far.
I'm assuming #646 will be merged first, as more urgent, and I bumped the version number accordingly.

Avoid collisions between module names

---

.circleci/config.yml
CHANGELOG.md
openfisca_core/base_functions.py
openfisca_core/columns.py
openfisca_core/commons.py
openfisca_core/data_storage.py
openfisca_core/decompositions.py
openfisca_core/decompositionsxml.py
openfisca_core/entities.py
openfisca_core/holders.py
openfisca_core/json_to_test_case.py
openfisca_core/model_api.py
openfisca_core/parameters.py
openfisca_core/periods.py
openfisca_core/reforms.py
openfisca_core/scenarios.py
openfisca_core/simulations.py
openfisca_core/taxbenefitsystems.py
openfisca_core/taxscales.py
openfisca_core/tools/__init__.py
openfisca_core/tools/test_runner.py
openfisca_core/variables.py
setup.py
tests/core/test_base_functions.py
tests/core/test_holders.py

Fixes #631
Fixes #632 
Python3 has deprecated a lot of elements present in python2 and in OpenFisca : 
- Regex ur"string" --> Regex r"string"
- No more Implicit imports --> explicit imports
- No more `basestring` or `unicode` types (all strings (`str`) are unicode) --> `text_unicode = u"".__class__` and `text_basestring = (str, text_unicode)` in type checking.
- `cmp` is an attribute of `sort()` --> Change `cmp` to `key` 
- `dict.iteritems()` --> `dict.items()`
- `asser_items_equal' --> equivalent assert equal expressions
To work with Python 3, it needs version 0.10.6dev of `biryani`
nosetests core/test_base_functions.py passes :tada:

Make OpenFisca more compatible with Python3

---

CHANGELOG.md
openfisca_core/tools/test_runner.py
setup.py

Fixes openfisca/openfisca-france#1016
Depends on #680 
- Use `PyYaml` `CLoader` and `CDumper` in `test_runner.py`
Yaml tests are slow
I changed `test_runner.py` to use `CLoader` and `CDumper`, and tested against `OpenFisca-France`.
In https://circleci.com/gh/openfisca/openfisca-france/1829, I launched:
pip install --editable .[test] --upgrade
time for i in {1..10}; do openfisca-run-test `circleci tests glob tests/mes-aides.gouv.fr/**/*.{yaml,yml} | circleci tests split`; done
Which gave the results
90.897
91.777
88.891
86.971
86.612
86.930
87.707
86.335
87.587
87.911
86.571
85.943
86.235
86.842
86.098
89.159
91.572
85.955
85.165
85.336
81.625
79.279
81.266
81.764
83.435
85.062
83.390
83.657
83.077
82.781
N   min     max     sum     mean    stddev
30  79.279  91.777  2575.83 85.861 …

Use PyYaml CLoader and CDumper in test_runner.py

---

CHANGELOG.md
openfisca_core/holders.py
setup.py
tests/core/test_holders.py

Fixes #676 
* Allow to set uncached variables when using a `memory_config`
- Previously, trying to set variables listed in `variables_to_drop` of the `memory_config` had no effect.
- Now this variables are still not cached, but they can be set by the user.

Allow to set uncached variables when using a memory_config

---

CHANGELOG.md
openfisca_core/entities.py
openfisca_core/simulations.py
setup.py
tests/web_api/basic_case/test_calculate.py

Connected to #669 
* In the error message sent to a user trying to set a variable without specifying for which period, add an example for a variable defined for `ETERNITY`.
For instance, if a user sends the following to the API:
```JSON
{
"persons": {
"Alicia": {
"birth": "1990-01-01"
}
},
"households": {
"_": {
"parents": ["Alicia"]
}
}
}
```
Before they would get:
```JSON
{
"persons": {
"Alicia": {
"birth": "Invalid type: must be of type object. Input variables must be set for specific periods. For instance: {\"salary\": {\"2017-01\": 2000, \"2017-02\": 2500}}"
}
}
}
```
After, the would get:
```JSON
{
"persons": {
"Alicia": {
"birth": "Invalid type: must be of type object. Input variables must be set for specific periods. For instance: {'salary': {'2017-01': 2000, '2017-02': 2500}}, or …
```

Improve error message for variables defined for ETERNITY

---

CHANGELOG.md
setup.py

- Require `psutil` version 5.4.6
- Installation fails with Python 3.7.0 on Windows
See https://github.com/openfisca/openfisca-senegal/pull/10#discussion_r201389882

Update psutil version to 5.4.6

---

CHANGELOG.md
openfisca_core/taxbenefitsystems.py
setup.py
tests/core/test_reforms.py

Fixes #465 
* Introduce `TaxBenefitSystem.replace_variable`
- Unlike `update_variable`, this method does _not_ keep any of the replaced variable in the new one.
- See [reference documentation](https://github.com/openfisca/openfisca-core/blob/add-replace-variable/openfisca_core/taxbenefitsystems.py#L125-L133).

Introduce TaxBenefitSystem.replace_variable

---

CHANGELOG.md
openfisca_web_api_preview/app.py
setup.py

connected to core #683 
This PR fixes the web API tracking so that the user's IP will be sent to the tracker even when the requests goes through a proxy (nginx)
- Adds a condition to send the first IP of the  `'X-Forwarded-For'` variable set by nginx, as the user's IP.

Track user ip through proxy

---

CHANGELOG.md
openfisca_web_api_preview/app.py
openfisca_web_api_preview/loader/__init__.py
openfisca_web_api_preview/loader/spec.py
openfisca_web_api_preview/scripts/serve.py
setup.py

Connected to #615 
* On the Web API, expose a welcome message (with a 300 code) on `/` instead of a 404 error.
For instance, `curl -i localhost:5000` gives:
```
HTTP/1.1 300 MULTIPLE CHOICES
(...)
{
"welcome": "This is the root of an OpenFisca Web API. To learn how to use it, check the general documentation (https://openfisca.org/doc/api) and the OpenAPI specification of this instance (http://localhost:5000/spec)."
}
```
* This message can be customized:
If the Web API is started with `openfisca serve -p 3000 --welcome-message "Welcome to the OpenFisca-France Web API. To learn how to use it, check our interactive swagger documentation: https://fr.openfisca.org/legislation/swagger."`
Then `curl -i localhost:5000` gives:
```
HTTP/1.1 300 MULTIPLE CHOICES
(...)
{
"welcome": "Welcome to the …
```

Make API discoverable from the root

---

CHANGELOG.md
openfisca_core/tools/__init__.py
openfisca_web_api_preview/app.py
setup.py

Fixes #699 
- Addresses the typecasting made when outputing numbers in the API and in `openfisca-run-test` from `float32` to `float64`.
- The typecasting added random decimal numbers that bring no extra value to users.

Keep float as float32 when outputting them

---

CHANGELOG.md
openfisca_web_api_preview/app.py
openfisca_web_api_preview/loader/__init__.py
openfisca_web_api_preview/loader/parameters.py
setup.py
tests/web_api/test_parameters.py

Fixes #709
- Revert the undesired side effects of `23.4.0` on the `parameters/` overview route of the Web API
- This route now behaves the exact same way than before `23.4.0`
- The keys of the `/parameters` JSON object are back to using the `.` notation
- Parameter nodes are for now not exposed in the `/parameters` overview (but each of them is exposed in `/parameter/path/to/node`)

Revert side-effects of 23.4.0 on  parameters overview route

---

.gitignore
CHANGELOG.md
openfisca_web_api/app.py
openfisca_web_api/loader/__init__.py
openfisca_web_api/loader/entities.py
openfisca_web_api/openAPI.yml
setup.py
tests/web_api/test_entities.py
tests/web_api/test_spec.py

Fixes #561 
- Get information on a country package's entities, and their roles
- Introduce the `/entities` endpoint for the Web API
```json
{
"description": "[...]",
"plural": "households",
"roles": {
"parent": {
"description": "The one or two adults in charge of the household.",
"mandatory": "true",
"max": 2,
"plural": "parents"
},
"child": {
"description": "Other individuals living in the household.",
"mandatory": "false",
"plural": "children"
}
}
}
```

 Add a `/entities` endpoint to the API

---

.circleci/config.yml

This adds a separate CircleCI job common to Python2 and Python3 for checking whether the version number has been bumped in `setup.py` and Changelog was updated.
Rationale:
- we get faster and more relevant feedback on our work while a PR is in progress
- we get highly relevant feedback when Python2 and Python3 tests behave differently
- the version check provides information of a different nature than functional tests
Testing: this PR is tested by introducing a "functional" change (swapping two lines in Core that do not have any ordering dependency, a change with no effect but that is picked up by the diff in the version check), which induces the version check to fail. This commit is then reverted, getting back to green as CircleCI configuration changes are not considered "functional".

Check version and Changelog separately

---

.gitignore
CHANGELOG.md
openfisca_core/parameters.py
openfisca_core/variables.py
openfisca_web_api/loader/parameters.py
openfisca_web_api/loader/variables.py
setup.py
tests/core/test_parameters.py
tests/web_api/test_parameters.py
tests/web_api/test_variables.py

Connected to openfisca/legislation-explorer#124
Allow for multiline editorial content on parameters and variables:
- Introduce `ParameterNode.documentation`, `Parameter.documentation` and `Variable.documentation` attributes
- User can access a `documentation` attribute through Web API
- on `/parameter` nodes as `/parameter/benefits`
> = python `ParameterNode.documentation`  
> = `documentation` string attribute of `index.yaml`
- on `/parameter` leafs as `/parameter/benefits/housing_allowance`
> = python `Parameter.documentation`  
> = yaml `documentation` string attribute
- on `/variable` leafs as `/variable/housing_allowance`
> = python `Variable.documentation`
- on every `/variable` leaf formula 
> = python `Variable` formula docstring
Here is web API `/variable/housing_allowance` …

Add editorial content on parameter and variable

---

CHANGELOG.md
openfisca_core/scripts/simulation_generator.py
openfisca_core/simulations.py
setup.py
tests/core/test_calculate_output.py

Fixes #726 
In Python, simplify simulation initialisation:
Before:
```py
simulation = ...
holder = simulation.persons.get_holder('salary')
holder.set_input('2018-08', [4000])
```
Now:
```py
simulation = ...
simulation.set_input('salary', '2018-08', [4000])
```

In Python, simplify simulation initialisation

---

CHANGELOG.md
openfisca_core/variables.py
setup.py
tests/core/test_variables.py
tests/web_api/test_trace.py

Relates to #701 
Bug detected by sending `https://fr.openfisca.org/legislation/swagger` example for `/trace` endpoint to local web api. The web api answer was:
`{"error":"Internal server error: Object of type bytes is not JSON serializable"}`
---
- Fix an encoding bug of variables with value type str
- Details:
* `str` corresponds to `unicode` in Python 2.7 and `bytes` in Python 3.7
* Set encoding with `numpy.unicode_` to dynamically cast to `unicode` both in Python 2.7 and Python 3.7
---
*Note:*
A numpy array containing values for a variable with `value_type = str`, automatically converts the values to:
* `numpy.str_` in Python 2.7
* `numpy.bytes_` in Python 3.7
In this PR, we update such variables `dtype` in `openfisca_core/variables.py` and this dtype gives:
*  `numpy.bytes_` for `|S` …

Fix type value for string variables

---

CHANGELOG.md
openfisca_core/variables.py
setup.py

Fixes #737 
- Bug fix 
- Restore string variables `max_length` in numpy encoding
- This restores `max_length` shortening effect on longer str variables values

Restore max_length shortening effect on variable of type str

---

CHANGELOG.md
openfisca_web_api/app.py
setup.py
tests/web_api/test_calculate.py
tests/web_api/test_trace.py

- Fix the internal server error that appeared for the  `/trace` and (less frequently) `/calculate` route of the Web API
- This error appeared when a simulation output was a variable of type string

Fix trace and calculate endpoints responses for str variables

---

CHANGELOG.md
openfisca_core/parameters.py
setup.py

- Nodes in the parameter hierarchy are now allowed to contain no data at all
Rationale: previously, 11 files in the France parameter hierarchy contained no data and only a single element of metadata, the `reference` field, set to the arbitrary and non-informative value `openfisca`. These were removed by openfisca/openfisca-france#1162 but this breaks parameter validation. Since `reference: openfisca` has zero informational content, I infer the unstated requirement that parameter nodes are allowed to contain no data at all. This introduces a test and a fix for that condition.

Allow empty parameter node files

---

CHANGELOG.md
openfisca_core/taxbenefitsystems.py
openfisca_web_api/app.py
openfisca_web_api/handlers.py
openfisca_web_api/loader/__init__.py
openfisca_web_api/loader/spec.py
openfisca_web_api/openAPI.yml
setup.py

Connected to #664 
Country package maintainers can define which examples they want to use in their OpenAPI spec the following way: https://github.com/openfisca/country-template/compare/define-openapi-ex
If no example has been defined:
- An arbitrary parameter is used for the `/parameter` route example
- An arbitrary variable is used for the `/variable` route example
- No example is shown for the `/calculate` and `/trace` routes. Instead, a text message such as the following is displayed:

Use country package specific examples in the /spec route

---

CHANGELOG.md
openfisca_web_api/app.py
openfisca_web_api/openAPI.yml
setup.py

- Fix `host` property in the OpenAPI `/spec`
- It should not contain the scheme (e.g. `http`)
- Infer scheme from request
- Before, we would assume `https`, which is not always accurate

Fix OpenAPI spec host and schemes

---

CHANGELOG.md
Makefile
setup.cfg
setup.py

- Use `pytest` to run tests.
- Declare `nose` a dependency so dependee libraries can move away from `nose`.
- `nose` is in maintenance mode
- `nose2` was a spin-off of `unittest2`
_Note: `openfisca-run-test` still depends on nose._

Use PyTest

---

.circleci/has-functional-changes.sh
Makefile

- Avoid race condition on CircleCI while formatting before linting
- By doing so, style errors were being overlooked

Do not format style before check

---

CHANGELOG.md
openfisca_core/parameters.py
openfisca_core/tools/test_runner.py
setup.py

- Improve the warning message incentivizing users to install `libyaml`
- `pyyaml` need to be fully reinstalled to use `libyaml`

Improve libyaml doc

---

.circleci/config.yml

Fixes #759 
- Use branch name in CircleCI's cache identifier

Use branch name in CircleCI's cache identifier

---

CHANGELOG.md
setup.py

PyTest 4 is currently breaking CI builds, this PR limits the range of PyTest versions to < 4.0 to avoid that.

Cap PyTest version to avoid failures

---

CHANGELOG.md
setup.py

Applies learning from #772 
Make sure to cap all dependency versions, in order to avoid unwanted functional and integration breaks caused by external code updates.

Cap all dependency versions

---

CHANGELOG.md
openfisca_core/parameters.py
setup.py
tests/core/test_parameters.py

- Allow `ParameterNode` children to have a numeric keys
- Before, an incorrect id would be set for these children, resulting to inconsistencies in the Web API.

Allow ParameterNode children to have a numeric keys

---

CHANGELOG.md
openfisca_core/entities.py
setup.py
tests/web_api/test_calculate.py

Fixes https://github.com/openfisca/openfisca-france/issues/1197
- In `Entity.init_from_json/init_variable_values`, attempting to assign a value larger than MaxInt32 resulted in a somewhat cryptic OverflowError.
- This PR fixes that, and also nudges the language away from "Invalid X", which blames the user for a deficiency of the software, and towards "Can't handle X", which acknowledges the deficiency.
This PR does NOT as yet include a test. The presumed fix for the issue consists of catching OverflowError in `init_variable_values`. However:
- `init_variable_values` has no existing unit tests
- its caller, `init_from_json` has no existing unit tests
- it's not possible to instantiate the class Entity in isolation - it requires a Simulation, which in turns require a TaxBenefitSystem, which …

Deal with OverflowError

---

CHANGELOG.md
openfisca_core/scripts/openfisca_command.py
openfisca_web_api/scripts/serve.py
setup.py

Fixes #634 
We need to be able to specify host as well as port in `openfisca serve`.
Absent a specific `host` option, `openfisca serve --bind 0.0.0.0:7777` will do, as the [documentation](https://openfisca.org/doc/openfisca-python-api/openfisca_serve.html) hints at.
Discoverability of this was limited in two ways:
- the bare command `openfisca` crashed with `AttributeError: 'Namespace' object has no attribute 'vars'`
- the help option `openfisca serve -h` does not mention gunicorn's `--bind`
This PR fixes both shortcomings.

Improve serve command

---

CHANGELOG.md
openfisca_core/parameters.py
setup.py
tests/core/test_extensions.py

Fixes #762 
- In `parameters.py`, there is rampant duplication of the following two lines:
```Python
self.children[child_name] = child
setattr(self, child_name, child)
```
However, in a few cases - including merging parameters from extensions, as in the issue referenced - the array is written to, without the call to setattr taking place. This will result in an inconsistent state and a ParameterNotFound exception even though the parameter seems to have been correctly loaded. This PR aims to channel all additions of a descendant to a parameter node via add_child.

Fix inconsistent access to sub-parameters

---

CHANGELOG.md
openfisca_core/columns.py
setup.py
tests/core/test_holders.py

Fixes #463
- Allow non-integral inputs to int variables
-----
The unit test included in this PR shows that a Holder will happily accept an array of float as an input to an `int` variable.
The underlying cause here is that parsing test cases still relies on `scenarios` which we would like to drop support for, per #716. Scenarios in turn rely on `columns`, of which [the code says they are "considered deprecated"](https://github.com/openfisca/openfisca-core/blob/56e31c6186e1e354d074ee1e6f4f760442b44981/openfisca_core/columns.py#L16). Columns and scenarios rely on `conv`, which I understand is our main remaining link with [Biryani](https://github.com/etalab/biryani). We have been saying for a while that we intend to drop Biryani, e.g. #691.
This looks like a textbook case for applying the …

Allow non-integral inputs to int variables

---

CHANGELOG.md
openfisca_core/simulations.py
setup.py

- Introduce `simulation.get_known_periods(variable)`
- Allows for to know the periods a variable is known from a simulation (already exist for the holder). 
Fix #788

Simulation get known periods

---

CHANGELOG.md
openfisca_web_api/app.py
setup.py

By default, FLASK sorts the JSON keys of the API responses. This PR opts out of this behavior.
~~In some use-cases (merge with IPP parameters in France), having the same orders in API responses that in the parameter YAML files avoid extra work and boilerplate.~~
---
Edit by @maukoquiroga 2018-12-09:
I'm ok with the fact that we don't order an object defined as unordered by the JSON specification. However, as discussed in the comments, I omitted any mention of use-case from the motivation of this PR's introduced changes.

Don't sort JSON keys in the Web API

---

CHANGELOG.md
setup.py

- Explicit test runner dependencies in Python 2.7
- Using an older version of `ruamel` caused a `'CommentedSeq' object has no attribute 'get'` error.

Explicit test runner dependencies in Python 2.7

---

CHANGELOG.md
openfisca_core/tools/test_runner.py
setup.py
tests/core/yaml_tests/test_failure.yaml

#781 caused the test runner to check only the first variable in a YAML test:
https://github.com/openfisca/openfisca-core/blob/61db5102bcce7fb973ae5c98df0042550dfc6b94/openfisca_core/tools/test_runner.py#L238-L255
On L245, the "return" exits the `_run_test` function after the first checked variable.
This PR fixes that, and changes `tests/core/yaml_test/test_failure.yaml` to cover this regression.

Fix test runner

---

CHANGELOG.md
openfisca_core/taxbenefitsystems.py
setup.py

- Load extensions more reliably, by removing dead code in load_extension
Partial solution to, connected to #801
When @guillett was trying to run a test that invoked an extension, this would fail when invoking `openfisca-run-test` (and would likely have failed with `openfisca test` as well) from the root directory of the extension's repo. This was because `load_extension` looked at directories, found a directory of the same name as the extension, and then went on to enumerate all packages installed under that directory with setuptool's `find_package`. `load_extension` would in that case consider the *first* such package to be the requested extension, which was an incorrect assumption; the extension would thus silently fail to load, leading to the unexpected error.

Load extensions more reliably

---

CHANGELOG.md
openfisca_core/tracers.py
setup.py
tests/core/test_tracer.py

- Add tracer format log test to ensure no regression occur
As an intense user of the tracer log I would like to make sure that this feature is kept as is or at least to be notified when changed.
Sublime text allows OK navigation:

Add test for tracer log

---

CHANGELOG.md
openfisca_core/tracers.py
setup.py

- Quell a warning in the build of [openfisca-doc](https://github.com/openfisca/openfisca-doc) by moving a docstring to the right place

Move docstring

---

CHANGELOG.md
openfisca_core/parameters.py
openfisca_core/taxscales.py
setup.py
tests/core/test_tax_scales.py

- Allow France to model "Chèque Energie" in a cleaner way:
- Introduce SingleAmountTaxScale (SATS), a simpler form of MarginalAmountTaxScale (MATS)
- whereas MATS sums the values in brackets, up to the amount subject to the scale, SATS only "looks up" the appropriate value for the amount subject to the scale, and is thus the simpler mechanism
- use `numpy.digitize`, allowing callers to specify right or left intervals
- introduce a `type` tag in `brackets` object, thus far with only `single_amount` allowed
- Rename AmountTaxScale to MarginalAmountTaxScale and make it inherit from SATS
This is non-breaking, as there are no direct clients of these classes outside of Core.

Introduce LookupTaxScale

---

CHANGELOG.md
openfisca_core/errors.py
openfisca_core/simulations.py
openfisca_core/tools/test_runner.py
setup.py
tests/core/test_runner/test_yaml_runner.py
tests/core/test_simulations.py

Fixes #801
- Outputs a more helpful message when a variable checked in a test doesn't exist
- Introduces unit tests for the test runners

Fix message output by test runner when a variable is unknown

---

CHANGELOG.md
openfisca_core/scripts/openfisca_command.py
openfisca_core/scripts/run_test.py
openfisca_core/taxscales.py
openfisca_core/tools/test_runner.py
setup.py

- Introduce `openfisca test --pdb`
- Allows for dropping into debugger on failures or errors
- Example : 
```
test --pdb --country-package openfisca_country_template path/to/country/template/tests
..........................ERROR:openfisca_core.tools.test_runner:age.yaml
> /path/to/openfisca-core/openfisca-core/openfisca_core/tools/__init__.py(44)assert_near()
-> diff, absolute_error_margin)
(Pdb)
```

Add debugger option to openfisca test

---

CHANGELOG.md
openfisca_core/periods.py
openfisca_core/scripts/remove_fuzzy.py
setup.cfg
setup.py
tests/core/parameters_fancy_indexing/test_fancy_indexing.py
tests/web_api/test_parameters.py
tests/web_api/test_variables.py

- Update autopep8 and flake8, which in particular now enforce rules W504 and W605
- W504 goes against house style, so we add it to ignored rules
- W605 may seem like an [overreach](https://github.com/PyCQA/pycodestyle/issues/755) but does make sense (additional details in PR description), so we upgrade a few regexes to raw strings
in Python strings the character "\" normally introduces an escape sequence, and should be followed by only a few select characters (\n is newline, \t is tab, and there are a few more esoteric ones) - anything else, for instance "\d", is an "illegal escape sequence" and should normally require a double escape (i.e. "\\d").
However, in regular expressions (where "\d" is a common way to say "any digit from 0 to 9") this would be quite burdensome, and Python in fact …

Update autopep8 and flake8

---

CHANGELOG.md
setup.py
tests/core/parameter_validation/test_parameter_validation.py
tests/core/test_periods.py
tests/core/test_reforms.py
tests/core/test_tracer.py
tests/web_api/test_calculate.py
tests/web_api/test_parameters.py
tests/web_api/test_variables.py

Fixes #834 
- Convert tests that were incompatible with Pytest 4.0+ and reported "xfail" when run with that version

Convert tests that were incompatible with Pytest 4.0+

---

CHANGELOG.md
openfisca_core/simulation_builder.py
setup.py
tests/core/test_simulation_builder.py
tests/web_api/test_calculate.py

Fixes #667 
Supersedes #785 
No longer raise an error when a group entity is not specified in a test case, or partially specified (only a subset of all persons is allocated to a group). Instead, each person is by default allocated to a group of which they are the sole member, with the default role in that group.

Relax rules on allocation to group entities

---

CHANGELOG.md
openfisca_core/holders.py
openfisca_core/simulation_builder.py
openfisca_core/simulations.py
setup.py
tests/core/test_variables.py

Hi everyone,
I want to design a reform where all non-contributive taxes and benefits (e.g. income tax, housing benefits, family benefits, social benefits etc.) are neutralized. I want this reform to apply only from a given date.
What I tried to do : 
- The `neutralize_variable` function and the related attribute `is_neutralized` cannot help me with that. They apply for all periods (either a variable is always neutralized either it is never).
- So I tried a solution with the `end` attribute from `Variable`. But it turns out that it does not work for "input" variables. 
Example : *I provide a value for a variable for period `"2019"` and then I code a reform that create an end date for this variable which is equal to `"2018-12-31"`. If I ask OpenFisca to calculate this variable for period …

Fix end date application

---

.circleci/config.yml
CHANGELOG.md
Makefile
setup.cfg
setup.py

- Make running Pytest more useful and less annoying

Restrict some Pytest options to 'make test', not all Pytest runs

---

CHANGELOG.md
openfisca_core/scripts/migrations/v24_to_25.py
openfisca_core/tools/test_runner.py
openfisca_web_api/loader/spec.py
setup.py
tests/core/test_axes.py
tests/core/test_entities.py
tests/core/test_simulation_builder.py

- Consistently use the safe approach to YAML loading, fixing [this deprecation warning](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) introduced in PyYAML 5.1

Always use safe_load to load YAML data

---

CHANGELOG.md
openfisca_core/simulation_builder.py
openfisca_core/simulations.py
openfisca_core/taxbenefitsystems.py
openfisca_core/tools/simulation_dumper.py
openfisca_core/tools/test_runner.py
openfisca_web_api/handlers.py
setup.py
tests/core/test_base_functions.py
tests/core/test_calculate_output.py
tests/core/test_countries.py
tests/core/test_cycles.py
tests/core/test_dump_restore.py
tests/core/test_formulas.py
tests/core/test_holders.py
tests/core/test_opt_out_cache.py
tests/core/test_reforms.py
tests/core/test_simulation_builder.py
tests/core/test_simulations.py
tests/core/test_variables.py

- Remove argument `simulation_json` of `Simulation` constructor, which was deprecated as of Core 25
- Remove keyword arguments from Simulation constructor, which should be called only from SimulationBuilder; introduce a property for `trace`
- Remove `period` attribute of Simulation
- As of Core 25, the preferred way of constructing new Simulation instances is via SimulationBuilder, any remaining uses of scenarios should be migrated to that API first.
- Any period attribute of the Simulation was coming from the simulation data (test case or JSON structure), use that instead of the attribute in the Simulation instance.
- Any keyword arguments of Simulation that you were using (or passing to Simulation-constructing methods) can now be accessed directly or as properties, `trace` being the …

Remove simulation_json argument to Simulation constructor

---

CHANGELOG.md
openfisca_core/simulations.py
setup.py

- Fix `AttributeError: 'Simulation' object has no attribute 'debug'`
- Error detected on `build` step in openfisca/openfisca-france#1293
> Unlink `debug` and `Tracer` init on simulation clone. If you clone a simulation with `debug = True`, it will not activate the `trace` attribute anymore.

Fix AttributeError on simulation

---

CHANGELOG.md
openfisca_core/simulations.py
openfisca_core/tracers.py
setup.py
tests/core/test_cycles.py

* Breaking change
* Improve cycle and spiral detection, giving consistent results more systematically
* Migration instructions:
- remove all optional parameters `max_nb_cycles`
- avoid relying on cached values of a computation (especially wrong values)
--------
Terminology:
- a "cycle" describes the situation where computing an OpenFisca variable for a given period eventually triggers the computation of the same variable for the same period; this cannot be resolved, so an exception is raised and the computation is aborted;
- a "spiral" is a related situation where computing a variable for a given period requires computing the same variable for a different period.
This PR makes that distinction more explicit by the type of exception raised.
Previously it was the responsibility of callers …

Ensure consistent results in the presence of "spirals"

---

CHANGELOG.md
openfisca_core/entities.py
openfisca_core/simulation_builder.py
openfisca_core/simulations.py
openfisca_core/tools/test_runner.py
openfisca_web_api/handlers.py
setup.py
tests/core/test_yaml.py

- Apply `flake8-bugbear` recommendations

Apply general spring style formatting 🌻

---

CHANGELOG.md
openfisca_core/holders.py
setup.py
tests/core/test_holders.py
tests/core/test_parameters.py
tests/web_api/case_with_extension/test_extensions.py
tests/web_api/test_calculate.py
tests/web_api/test_entities.py
tests/web_api/test_headers.py
tests/web_api/test_helpers.py
tests/web_api/test_parameters.py
tests/web_api/test_spec.py
tests/web_api/test_trace.py
tests/web_api/test_variables.py

Fixes #841 
When a user tries to set an input for a variable for several months (or several years), but the variable has no `set_input` declared, raise an error instead of ignoring the input.
> I couldn't resist removing some nose dependencies on the way. The real changes brought by this PR are in `holders.py` and `test_holders.py`.

Do not ignore inputs for several months or years

---

CHANGELOG.md
openfisca_core/indexed_enums.py
openfisca_core/simulations.py
setup.py
tests/core/test_holders.py

Allow the use of Enum values in comparisons, working around our abuse of the Python module system for TaxBenefitSystem loading.
Tested by updating `test_holders.py` to import HousingOccupancyStatus instead of getting `possible_values`. (Also tested, outside of CI, against the YAML test in [this branch](https://github.com/openfisca/openfisca-france/compare/double-import-error) of France.)

Improve usability of Enum values

---

CHANGELOG.md
openfisca_web_api/app.py
setup.py
tests/web_api/test_spec.py

The "Try it out" feature of [Swagger](https://fr.openfisca.org/legislation/swagger) in the legislation explorer currently doesn't work.
This bug was previously fixed, but we inadvertently reverted the fix while removing the Python 2 adaptations.

Fix swagger host

---

CHANGELOG.md
openfisca_core/parameters.py
setup.py
tests/core/parameter_validation/duplicate_key.yaml
tests/core/parameter_validation/test_parameter_validation.py
tests/core/parameters_fancy_indexing/test_fancy_indexing.py

- Duplicate keys in YAML parameters files now raise an error
- Before, only one of the two values declared was taking into account, while the other was silently ignored
- Duplicate keys are easy to introduce by mistake while editing parameters files. They can cause bugs that are hard to detect immediately, and result in ambiguities in the code base that are hard to fix afterwards.
This implementation has no performance impact on the loading of the parameters file.
> For the record, a first approach trying to use `ruamel.yaml` instead of `pyyaml` ended up degrading the loading time (with C loader) by a factor of almost 2, and was abandoned.

Raise an error when keys are duplicated in parameters files

---

CHANGELOG.md
openfisca_core/simulation_builder.py
setup.py
tests/core/test_simulation_builder.py

- Support role indices in SimulationBuilder.join_with_persons
- This broadens the range of input data we can handle, at some risk of misattributing roles

Support role indices in join_with_persons

---

CHANGELOG.md
openfisca_core/simulations.py
setup.py
tests/core/test_formulas.py

- Allow formulas to return scalar values; broadcast these values to population-sized arrays
Note that the check for "formulas must return an array" was not unit tested and included, also untested, functionality to check for NaNs in debug mode; this is removed by that PR.
This fixes the underlying issue of #853 - a formula can now compute a value derived from a parameter, for use in a vector computation.

Allow formulas to return scalar values and broadcast

---

CHANGELOG.md
openfisca_core/simulation_builder.py
setup.py
tests/core/test_simulation_builder.py

- Fix incomplete initialization of group entities provided by default when not supplied in YAML tests
Fixes #849

Fix default group entity

---

CHANGELOG.md
openfisca_core/data_storage.py
openfisca_core/rates.py
setup.py

- Define a trim option for average rate function.
- Convert a dict_values to a list (left-over by the python 3 migration)
- Use a less stric version dependency for `psutils`. Problem arising with `psutils` are mainly due to freeze at install. Use `pip` option `--no-cache-dir` if you face troubles at install.

Misc ipp fix

---

.gitignore
CHANGELOG.md
Makefile
openfisca_core/parameters.py
openfisca_core/periods.py
openfisca_core/populations.py
openfisca_core/tools/test_runner.py
setup.cfg
setup.py

Extracted from #871 
Typing remains optional: the type checker will only make sure that the optional annotations are consistent with the code.
Why typing ? 
- Useful as documentation: methods are easier to understand when the input and outputs type are explicit
- Allows to detect some bugs early (works better when there are more annotations in the code)
- See https://www.youtube.com/watch?v=pMgmKJyWKn8 for more 🙂

Enforce type checking in tests and CI

---

CHANGELOG.md
openfisca_core/tracers.py
setup.py
tests/core/test_tracers.py

Fixes #898
Fixes #899
Fixes openfisca/openfisca-france#1360
Alternative solution to #898 
- Fix serialisation error introduced in [34.2.9](https://github.com/openfisca/openfisca-core/tree/34.2.9) in route `/trace` (Web API)
- This was causing an Internal Server Error
- Notably, `numpy` arrays were not being parsed correctly as not JSON serialisable

Fix serialization error

---

CHANGELOG.md
openfisca_core/periods.py
openfisca_core/populations.py
openfisca_core/simulations.py
setup.py

Fix minor errors that result in operations being uselessly repeated over and over.

Improve performances

---

CHANGELOG.md
setup.py

* Fix syntax in `README` code example for v.21.2.0 new feature
* Explicit that the `MemoryConfig` configures a `Simulation` instance
> ~No need to bump the version for this PR.~ (the changelog is listed in the functional changes)

Fix v.21.2.0 example on memory config

---

CHANGELOG.md
setup.py

Fixes #910
- Remove the library `enum34` from requirements
- The library `enum34` provides a backport of >= 3.4 `enum` to >= 2.7, < 3.4 Python environments.
- The standard `enum` and `enum34` are hence incompatible as installed under the same path.
- Since we dropped support for <= 3.6, that library is no longer needed.

Remove incompatible library enum34

---

CHANGELOG.md
openfisca_web_api/scripts/serve.py
setup.py

Fixes #913 
- Refactor the use of the now-deprecated `gunicorn.six` module.
- In versions < 20, [gunicorn](http://docs.gunicorn.org/en/19.3/custom.html) provided the `gunicorn.six` module.
- In version >= 20, this [gunicorn](http://docs.gunicorn.org/en/stable/custom.html) module has been deprecated.
- This pull request adapts `openfisca serve` code to the new gunicorn API.

Refactor use of deprecated gunicorn.six

---

CHANGELOG.md
setup.py

- Downgrade numpy version's upper bound to 1.17
- Details:
- Numpy 1.18 deprecates the use of several of its methods.
- Changes in `numpy.select` have impacted other packages depending on OpenFisca Core.

Downgrade Numpy to 1.17

---

CHANGELOG.md
openfisca_core/taxscales.py
setup.py

- Use `asarray` in `taxscales.py` when we know the argument is a `ndarray`.
- Details:
- It prevents `numpy` to copy the array if the `dtype` is compatible.

Use asarray in taxscales.py when we know arg is array

---

CHANGELOG.md
openfisca_core/taxscales.py
setup.py

- Add more explicit typing annotations for `ndarrays`.

Improve taxscales.py typing

---

CHANGELOG.md
openfisca_core/indexed_enums.py
setup.cfg
setup.py

- Add typing to `indexed_enums.py`.
- Details:
- Type-annotate `ndarray` types to help contributors know the actual methods signatures.

Add typing to indexed_enums.py

---

CHANGELOG.md
openfisca_core/simulation_builder.py
setup.py

Part of #924 
- Annotates the expected type of the axis count in `SimulationBuilder`.

Document that we expect axis count to be an int

---

CHANGELOG.md
setup.py

- Fix `Werkzeug` library version (temporarily avoid its [yesterday update](https://pypi.org/project/Werkzeug/#history)).
Then migrate to latest version thanks to #945 
Could be tested by running the web api. Example : `openfisca serve -c openfisca_france`

Fix werkzeug dependency version

---

CHANGELOG.md
openfisca_web_api/app.py
setup.py

- Fixes web api loading to match latest `Werkzeug` dependency revision (`1.0.0`)
- Details:
- Preserve not merging double slashes by default.
- Update `ProxyFix` module loading and initialising arguments.
---
Detected error : `ModuleNotFoundError: No module named 'werkzeug.contrib'`
At : `openfisca_web_api/app.py", line 17, in <module> handle_import_error(error)`
When the server tried to load openfisca-france latest Web API.
Werkzeug dependency has recently been upgraded from `0.16.1` to `1.0.0` (see [pypi](https://pypi.org/project/Werkzeug/#history)) 
It is a sub-dependency of `Flask`:
```shell
$ pip install pipdeptree
(...)
$ pipdeptree -r -p Werkzeug
Werkzeug==1.0.0
- Flask==1.1.1 [requires: Werkzeug>=0.15]
- Flask-Cors==3.0.7 [requires: Flask>=0.9]
```
The old `ProxyFix` module name …

Fix web api after werkzeug upgrade

---

CHANGELOG.md
openfisca_core/commons.py
openfisca_core/taxscales.py
setup.py
tests/core/tax_scales/test_abstract_tax_scale.py
tests/core/tax_scales/test_linear_average_rate_tax_scale.py
tests/core/tax_scales/test_marginal_amount_tax_scale.py
tests/core/tax_scales/test_marginal_rate_tax_scale.py
tests/core/tax_scales/test_single_amount_tax_scale.py
tests/core/tax_scales/test_tax_scales_commons.py
tests/core/test_commons.py

- Deprecate `Dummy`.
- The functionality is now directly provided by `empty_clone`.
- Refactor abstract scales to use Python's `abc` lib.
- This allows for consistent inheritance, which wasn't the case before.

Use Python's ABC for abstracts

---

CHANGELOG.md
openfisca_core/simulation_builder.py
openfisca_web_api/handlers.py
openfisca_web_api/loader/spec.py
setup.py
tests/web_api/test_calculate.py
tests/web_api/test_spec.py

- Revert dpath bump introduced by #940 
- Fix bug in period interpretation by Web API (openfisca/openfisca-france#1413)
Use dpath `1.5.0` library `dpath.new` in [/calculate](https://github.com/openfisca/openfisca-core/blob/7fe1e45662fb1f5a238f05cc4c9db4adc9cd2c03/openfisca_web_api/handlers.py#L32) endpoint.
> To see the dpath `2.0.1` library `dpath.util.new` behaviour in [dpath documentation](https://github.com/akesterson/dpath-python), see this example: `dpath.util.new(x, 'a/b/e/f/h/13', 'Wow this is a big array, it sure is lonely in here by myself')`

Revert dpath bump

---

CHANGELOG.md
openfisca_core/tools/test_runner.py
setup.py

Fixes openfisca/country-template#89
- Fix `PytestDeprecationWarning` on `openfisca test` command
---
Bug description:
[pytest 5.4.0](https://docs.pytest.org/en/stable/changelog.html#pytest-5-4-0-2020-03-12) deprecates using direct constructors for test nodes. 
This feature is called by the `test_runner` that collects openfisca yaml tests.
So, before this fix, a user calling `openfisca test` (on the country-template for example) gets two warnings:
```
.../openfisca_core/tools/test_runner.py:245: X tests with warnings
.../openfisca_core/tools/test_runner.py:245: PytestDeprecationWarning: direct construction of YamlFile has been deprecated, please use YamlFile.from_parent
return YamlFile(path, parent, self.tax_benefit_system, self.options)
.../openfisca_core/tools/test_runner.py:102: Y tests …
```

Fix warnings on openfisca test command

---

CHANGELOG.md
Makefile
README.md
openfisca_core/formula_helpers.py
openfisca_core/simulation_builder.py
openfisca_core/tools/simulation_dumper.py
setup.py

Fixes #924
⚠️ As this is possibly a breaking change that affects every formula, this PR should be checked with at least one country model updated to numpy 1.18 as well (and the country-template is too simple to be a good example of the effect of this update 🙂).
---
`select` deprecations were described in [this comment](https://github.com/openfisca/openfisca-core/issues/924#issuecomment-615512006)
Add checks at `select` routine usage when a call to the function using `select` might lead to an empty condition.
No update on conditions types as we already used booleans.
---
- Bump `numpy` dependency to `1.18`

Upgrade numpy dependency to 1.18

---

CHANGELOG.md
Makefile
openfisca_core/entities.py
openfisca_core/variables.py
openfisca_web_api/app.py
openfisca_web_api/handlers.py
openfisca_web_api/openAPI.yml
setup.py
tests/web_api/test_dependencies.py
tests/web_api/test_parameters.py
tests/web_api/test_spec.py

Purpose
This new endpoint allows a user to find the dependent input variables to a variable. It's useful if you want to calculate a variable, and need to know what inputs you need. It allows you to find the answer to that question without having to manually go through all the variables (and their dependencies) until you get to the inputs.
It's also useful for gathering statistics about the use of input variables. If I want to design a form to get information from a user to assess their eligibility for a series of benefits, I could use this to find which input variables are used most often across different formulas, and put those at the start of the form. This could avoid having to ask the user too many questions, as you could design the form to exit early if the user isn't eligible.
I …

Add dependencies endpoint

---

CHANGELOG.md
setup.py
tests/web_api/test_parameters.py

- Fix web api test for a parameter node request with `/parameter` endpoint.
- Details:
- Untie the test from `OpenFisca-Country-Template` parameters list.
---
Dear reviewers, you will find a first commit that fixed the test without naming any specific `country-template` parameter. In the last changes, you will find the same checks with `basic_income` parameter and, even if it ties a bit the test to the `country-template` model, it seemed better (similar to other tests, easier to read). But we can rollback if you prefer.
Besides, as this PR doesn't affect functional changes, we shouldn't need to bump the package revision but it seemed better to name the version that fixes the tests.

Fix web api test on /parameter endpoint

---

CHANGELOG.md
openfisca_core/tools/__init__.py
setup.py
tests/core/tools/test_assert_near.py

- Extends assert_near to date comparison

Extends assert_near to date comparison

---

CHANGELOG.md
setup.py
tests/web_api/test_variables.py

- Fixes failing tests introduced by openfisca-core/country-template#97
- Fixes #980

Fix test_variable_documentation failing test

---

CHANGELOG.md
openfisca_core/parameters.py
openfisca_web_api/openAPI.yml
setup.py
tests/core/parameter_validation/array_type.yaml
tests/core/parameter_validation/test_parameter_validation.py

- Support arrays as parameters.
- Improves wrong parameter types error message.
- - -
This was added to move more constants into parameters. For example, in OpenFisca-France: https://github.com/openfisca/openfisca-france/blob/master/openfisca_france/model/caracteristiques_socio_demographiques/demographie.py#L3-L35
- - -
TODO :

Allow array parameters

---

.gitignore
README.md
tests/web_api/test_variables.py

- Test for presence of strings rather than exact matches in Web API responses, as most other Web API tests did.
- - -
Supersedes #986, re-implements #981, would have avoided #980.

Increase resilience of web API tests

---

CHANGELOG.md
openfisca_core/tools/test_runner.py
setup.py

Solves #956 
- Introduce max_spiral_loops option in YAML test files 
- Allows for control of spiral depth for every test
cc @magemax

Control max_spiral_loops via YAML test files

---

CHANGELOG.md
openfisca_web_api/app.py
setup.py
tests/web_api/test_calculate.py

Fixes #991
- [Web API] Gracefully handle unexpected errors 
- The exception signature expected by the internal server error handler was not the good one
- Henceforth no response was being given to the user, when a 500 with an explanation was expected

Gracefully handle unexpected errors

---

CHANGELOG.md
openfisca_core/simulations/simulation_builder.py
setup.py
tests/core/test_axes.py

- Repair expansion of axes on a variable given as input
- When expanding axes, the expected behavour is to override any input value for the requested variable and period
- As longs as we passed some input for a variable on a period, it was not being overrode, creating a NumPy's error (boradcasting)
- By additionally checking that an input was given, now we make that the array has the correct shape by constructing it with NumPy's tile with a shape equal to the number of the axis expansion count requested.
---
Updated by @maukoquiroga the 10/04/2021.

In SimulationBuilder, repair expansion of axes on a variable given as input

---

CHANGELOG.md
openfisca_core/experimental/memory_config.py
openfisca_core/parameters/config.py
openfisca_core/simulations/simulation.py
openfisca_core/tools/test_runner.py
openfisca_core/warnings/__init__.py
openfisca_core/warnings/libyaml_warning.py
openfisca_core/warnings/memory_warning.py
openfisca_core/warnings/tempfile_warning.py
setup.py

Fixes #995 
- Change logging.warning to warnings.warn to allow users of the package to hide them. See https://github.com/openfisca/openfisca-core/issues/995 for more info.
So the users could hide the warnings like this:
```python
warnings.simplefilter(action="ignore", category=TempfileWarning)
```

Change log.warning to warnings.warn to allow users of the package to hide them.

---

CHANGELOG.md
README.md
STYLEGUIDE.md
conftest.py
setup.py
tests/core/parameter_validation/test_parameter_clone.py
tests/core/test_axes.py
tests/core/test_calculate_output.py
tests/core/test_countries.py
tests/core/test_cycles.py
tests/core/test_dump_restore.py
tests/core/test_entities.py
tests/core/test_extensions.py
tests/core/test_formulas.py
tests/core/test_holders.py
tests/core/test_opt_out_cache.py
tests/core/test_parameters.py
tests/core/test_reforms.py
tests/core/test_simulation_builder.py
tests/core/test_simulations.py
tests/core/test_yaml.py
tests/core/tools/test_assert_near.py
tests/fixtures/entities.py
tests/fixtures/simulations.py
tests/fixtures/taxbenefitsystems.py
tests/fixtures/variables.py

Related to #969 (it is almost a subset of it, it only extracts CountryTaxBenefitSystem to a fixture).
Related to #984 (it adds more modularity but does not evince country template's scenarios).
- In tests, extract `CountryTaxBenefitSystem` to a fixture reusable by all the tests in the test suite.
- It allows for a better reusability of test scenarios available to new contributors.
- To mitigate possible performance issues, by default the fixture is initialised once per test module.
Impact on performance of the test suite is neglectable. 
Before:
```
openfisca-core[master] > time for i in {1..10}; do pytest; done
real	1m59.024s
user	1m42.614s
sys	0m27.081s
```
After:
```
openfisca-core[extract-tbs-fixture] >  time for i in {1..10}; do pytest; done
real	2m5.148s
user	1m46.425s
sys	0m28.280s …
```

Make CountryTaxBenefitSystem reusable as a fixture

---

CHANGELOG.md
openfisca_core/indexed_enums/enum.py
openfisca_core/indexed_enums/enum_array.py
openfisca_core/taxscales/abstract_rate_tax_scale.py
openfisca_core/taxscales/abstract_tax_scale.py
openfisca_core/taxscales/amount_tax_scale_like.py
openfisca_core/taxscales/helpers.py
openfisca_core/taxscales/linear_average_rate_tax_scale.py
openfisca_core/taxscales/marginal_amount_tax_scale.py
openfisca_core/taxscales/marginal_rate_tax_scale.py
openfisca_core/taxscales/rate_tax_scale_like.py
openfisca_core/taxscales/single_amount_tax_scale.py
openfisca_core/taxscales/tax_scale_like.py
openfisca_core/tracers/computation_log.py
openfisca_core/tracers/flat_trace.py
openfisca_core/tracers/full_tracer.py
openfisca_core/tracers/performance_log.py
openfisca_core/tracers/simple_tracer.py
openfisca_core/tracers/trace_node.py
openfisca_core/tracers/tracing_parameter_node_at_instant.py
openfisca_core/variables/config.py
setup.py

- Upgrade numpy dependency.
`numpy` can be compiled natively on darwin-arm64 from v1.20.1 on. OpenFisca thus needs to allow this version.
Some additional work is needed for installing on Apple Silicon M1 processors, which is documented [here](https://stackoverflow.com/questions/66768259/how-to-install-and-import-scipy-numpy-numexpr-and-others-on-m1-apple-silicon/66768260#66768260). I considered updating the README but concluded that the install procedure should be normalised in the coming months, and that it was not worth documenting transitory instructions in the README, and that this PR discussion would be sufficient.
I'm open to requests to include instructions in the README 🙂

Upgrade numpy to add support for M1 processors

---

CHANGELOG.md
openfisca_core/indexed_enums/enum.py
openfisca_core/indexed_enums/enum_array.py
openfisca_core/taxscales/abstract_rate_tax_scale.py
openfisca_core/taxscales/abstract_tax_scale.py
openfisca_core/taxscales/amount_tax_scale_like.py
openfisca_core/taxscales/helpers.py
openfisca_core/taxscales/linear_average_rate_tax_scale.py
openfisca_core/taxscales/marginal_amount_tax_scale.py
openfisca_core/taxscales/marginal_rate_tax_scale.py
openfisca_core/taxscales/rate_tax_scale_like.py
openfisca_core/taxscales/single_amount_tax_scale.py
openfisca_core/taxscales/tax_scale_like.py
openfisca_core/tracers/computation_log.py
openfisca_core/tracers/flat_trace.py
openfisca_core/tracers/full_tracer.py
openfisca_core/tracers/performance_log.py
openfisca_core/tracers/simple_tracer.py
openfisca_core/tracers/trace_node.py
openfisca_core/tracers/tracing_parameter_node_at_instant.py
openfisca_core/variables/config.py
setup.py

Fixes #1009
Supersedes  #1012
Depended on by #1010
- Drop latest NumPy supported version to 1.18.x
- OpenFisca relies on MyPy for optional duck & static type checking
- When libraries do not implement their own types, MyPy provides stubs, or type sheds
- Thanks to `__future__.annotations`, those stubs or type sheds are casted to `typing.Any`
- Since 1.20.x, NumPy now provides their own type definitions
- The introduction of NumPy 1.20.x in #990 caused one major problem: 
- It is general practice to do not import at runtime modules only used for typing purposes, thanks to the `typing.TYPE_CHEKING` variable
- The new `numpy.typing` module was being imported at runtime, rendering OpenFisca unusable to all users depending on previous versions of NumPy (1.20.x-)
- These changes revert #990 and …

Drop latest NumPy supported version to 1.18.x

---

CHANGELOG.md
openfisca_core/periods/config.py
setup.py
tests/core/parameter_validation/test_parameter_validation.py
tests/core/parameter_validation/wrong_date.yaml
tests/core/test_periods.py

Fixes #1005 
- Properly check for date validity in parameters
- Date validity was being checked only partially, allowing parameters with illegal dates such as "2015-13-32"
- The changes introduced fix this error and prevent the user when a parameter date is illegal

Validate date validity

---

CHANGELOG.md
openfisca_web_api/app.py
setup.py
tests/web_api/test_calculate.py

Connected to #916 
**Bug fix**:
- [Web API] Handle a period mismatch error:
- The exception expected by a period mismatch error was not the good one.
- A period mismatch error renders a 500 internal server error instead of a 400 bad request error since it's caused by the user.

Add period mismatch error handling to API

---

README.md

This PR adds instructions in the README for creating a python virtual environment and upgrading pip. While these are obvious for seasoned Python programmers, the lack of those instructions may throw off some people who might be willing to contribute to the project.

Add venv and pip commands to installation instructions

---

Makefile

- Document Makefile
- Add a comment to explain what each task does
- Print a human friendly message when running a task
```
$ make test
[⚙] Delete builds and compiled python files...
[⚙] Compile python files to check for syntax errors...
[⚙] Run linters to check for syntax and style errors...
[⚙] Run static type checkers for type errors...
Success: no issues found in 131 source files
[⚙] Run openfisca-core tests...
...
```

Document Makefile

---

.circleci/config.yml
CHANGELOG.md
Makefile
openfisca_core/tools/test_runner.py
openfisca_tasks/install.mk
openfisca_tasks/lint.mk
openfisca_tasks/publish.mk
openfisca_tasks/serve.mk
openfisca_tasks/test_code.mk
openfisca_tasks/test_doc.mk
setup.py

- Reorganise `Makefile` into context files (install, test, publish…)
- Colorise `make` tasks and improve messages printed to the user
This follows #1040 and is intended to help consolidate a unified workflow.

Improve Make UI and org

---

openfisca_tasks/publish.mk

The GitHub Actions set-up was merged and the build[ failed](https://github.com/openfisca/openfisca-core/runs/4078138534?check_suite_focus=true) with an `error: invalid command 'bdist_wheel`.
This PR installs the `wheel` package in the `build`.

Add install wheel to build

---

CHANGELOG.md
openfisca_core/populations/population.py
setup.py

This should fix #1072 . I'll add version change information, but the action seemed to fail quite quickly for some reason.
- Use `self.entity.key` rather than `self.key` when generating an error message for a mis-sized population array.

Fix message bug

---

CHANGELOG.md
openfisca_core/taxbenefitsystems/tax_benefit_system.py
setup.py

- Replace calls to deprecated `imp` module with `importlib` and `sys`. Fixes #1053.
I successfully ran `make test` locally.
Reopening #1087 cause of merge commit

Remove calls to deprecated imp module

---

CHANGELOG.md
setup.py

Connected to openfisca/openfisca-france#1808 where [test-api job fails](https://github.com/openfisca/openfisca-france/runs/5247747400?check_suite_focus=true) on GitHub Actions.
- Fix `openfisca-core` Web API error triggered by `Flask` dependencies updates
- Bump `Flask` patch revision to fix `cannot import name 'json' from 'itsdangerous'` on Web API.
- Then, fix `MarkupSafe` revision to avoid `cannot import name 'soft_unicode' from 'markupsafe'` error on Web API.
This PR fixes two issues:
**🐛`itsdangerous` revision fixed by `flask` upgrade**
This first one is about `itsdangerous` and was detected by the [test-api job](https://github.com/openfisca/openfisca-france/runs/5247747400?check_suite_focus=true): 
```shell
ImportError: OpenFisca is missing some dependencies to run the Web API: …
```

Fix Web API after Flask dependencies updates

---

CHANGELOG.md
openfisca_core/taxscales/marginal_rate_tax_scale.py
openfisca_core/taxscales/rate_tax_scale_like.py
setup.py
tests/core/tax_scales/test_marginal_rate_tax_scale.py
tests/core/tax_scales/test_rate_tax_scale_like.py

As suggested by @benjello, this PR is intended to allow, for a given tax scale, the determination of the tax rate according to the tax bracket indice.
This feature would be useful for a fix in `openfisca-france` : https://github.com/openfisca/openfisca-france/pull/1831#discussion_r835448750
- Introduce `rate_from_bracket_indice` method on `RateTaxScaleLike` class
- Allows for the determination of the tax rate based on the tax bracket indice

Feat add rate from bracket indice method to rate tax scale like

---

CHANGELOG.md
openfisca_core/populations/population.py
openfisca_core/reforms/reform.py
setup.py

Some docstring refs are ambiguous. Until now, these warnings were not raised. Following [updates](https://github.com/openfisca/openfisca-doc/pull/264) in the documentation generation system, these references now raise errors when compiled and block documentation updates. This changeset removes links that are ambiguous so that the documentation can be generated again.

Remove ambiguous docstring references

---

.conda/README.md
.conda/meta.yaml
.github/get_pypi_info.py
.github/workflows/workflow.yml
CHANGELOG.md
README.md
setup.py

Connected to #1105 (and [this comment](https://github.com/openfisca/openfisca-core/pull/1105#issuecomment-1135902404))
- The conda build failed on master because of a replacement in a comment string. I removed the `_` in the comment to avoid replace in comment. These replace is made by the script `.github/get_pypi_info.py` that get info from PyPi.
- With @sandcha we choose to remove the fonctionality that get dependencies from PyPi because it only works for main deps and not for extra requirements.

[conda] Fix comment replacement that crash conda build

---

openfisca_tasks/test_doc.mk

This changeset stops documentation compilation warnings from being treated as errors.
An untreatable warning appeared in the codebase since an update to Sphinx (the engine building the doc): `<unknown>:1: WARNING: py:obj reference target not found: openfisca_core.types.data_types.arrays.T`. Warnings are currently treated as errors when building the doc, meaning that the doc test always fails. For example, this failing CI is now blocking a PR as trivial as #1132.
Applying this changeset implies that additional, legitimate warnings will not be made easily visible in CI. This is however the only way I found after a lot of investigation to solve this situation. See https://github.com/openfisca/openfisca-doc/pull/264#issuecomment-1157868878.

Do not treat doc warnings as errors

---

CHANGELOG.md
openfisca_tasks/install.mk
openfisca_tasks/test_code.mk
setup.py

Fixes #1136 
- Fix pylint dependency in fresh editable installations
- Ignore pytest requirement, used to collect test cases, if it is not yet installed.

Fix pristine editable install

---

CHANGELOG.md
openfisca_core/holders/helpers.py
openfisca_core/holders/tests/test_helpers.py
setup.cfg
setup.py

Fixes govzeroaotearoa/openfisca-aotearoa#15
Depends on #1141 
- Introduce support for the ``day`` date unit in `holders.set_input_dispatch_by_period` and `holders.set_input_divide_by_period`
- Allows for dispatching values per day, for example, to provide a daily (week, fortnight) to an yearly variable.
- Inversely, allows for calculating the daily (week, fortnight) value of a yearly input.

Re-add support for dispatch/divide by days

---

.github/workflows/workflow.yml

Fixes #1163 
- Use the appropriate OS version in Github Actions
- Workflow was set to run on `ubuntu-latest` and `Python 3.7.12`
- `ubuntu-latest` changed from `ubuntu-20.04` to `ubuntu-22.04`
- As the latter does not ship with the aforesaid Python version, builds started to fail
- This changeset restore deterministic builds by setting OS explicitly to `ubuntu-20.04`

Use appropriate OS version in Github Actions

---

.github/workflows/workflow.yml
.gitignore
CHANGELOG.md
README.md
openfisca_tasks/install.mk
openfisca_tasks/lint.mk
openfisca_tasks/publish.mk
openfisca_tasks/test_code.mk
setup.py

Fixes #1158
- Lighter install by removing test packages from systematic install.

Remove constraint on packages

---

CHANGELOG.md
openfisca_core/parameters/parameter_scale.py
openfisca_core/parameters/parameter_scale_bracket.py
setup.py

Depends on #1160 
- ParameterScaleBracte:
- Remove base attribute
This attribute is unclear and was used only for some French social security contributions

Remove base attribute from ParameterScaleBracket

---

CHANGELOG.md
openfisca_core/holders/helpers.py
openfisca_core/periods/__init__.py
openfisca_core/periods/helpers.py
openfisca_core/periods/instant_.py
openfisca_core/periods/period_.py
setup.py

Depends on #1160 
- In _periods.Instant_:
- Remove `period`, method used to build a `Period` from an `Instant`.
- This method created an upward circular dependency between `Instant` and `Period` causing lots of trouble.
- The functionality is still provided by `periods.period` and the `Period` constructor.
- Replace `some_period.start.period` and similar methods with `Period((unit, some_period.start, 1))`.

Deprecate Instant.period

---

CHANGELOG.md
openfisca_core/commons/tests/test_formulas.py
openfisca_core/indexed_enums/enum_array.py
openfisca_core/variables/variable.py
setup.py

Part of #673 
- Unify casing of NumPy.

Unify casing of NumPy

---

CHANGELOG.md
openfisca_web_api/app.py
openfisca_web_api/loader/spec.py
openfisca_web_api/openAPI.yml
setup.py
tests/web_api/test_spec.py

Depends on #1160 
- Upgrade OpenAPI specification of the API to v3 from Swagger v2.
- Continuously validate OpenAPI specification.
- Drop support for OpenAPI specification v2 and prior.
- Users relying on the aforesaid can use [this](https://converter.swagger.io/api/convert?url=OAS2_YAML_OR_JSON_URL) to migrate ([example](https://web.archive.org/web/20221103230822/https://converter.swagger.io/api/convert?url=https://api.demo.openfisca.org/latest/spec)).
---
Last updated by @maukoquiroga at 2022-11-03T23:14:44Z

Upgrade OpenAPI spec to v3

---

CHANGELOG.md
openfisca_core/taxbenefitsystems/tax_benefit_system.py
setup.py

- Remove use of `importlib_metadata` to fix #1176 (by reverting part of #1165)

No importlib metadata

---

CHANGELOG.md
openfisca_core/tools/test_runner.py
setup.py
tests/core/tools/test_runner/test_yaml_runner.py

- Method `_get_tax_benefit_system()` of class `YamlItem` in file  `openfisca_core/tools/test_runner.py` will now clone the TBS when applying reforms to avoid running tests with previously reformed TBS.
In the case we want to run **2 tests or more** with differents `reforms` and no `extensions` we were sharing the same baseline so we were executing following tests with the TBS set in previous tests.

Fix YamlItem in test_runner.py to clone TBS in case of reforms

---

CHANGELOG.md
openfisca_core/taxbenefitsystems/tax_benefit_system.py
openfisca_core/variables/variable.py
openfisca_web_api/loader/spec.py
openfisca_web_api/loader/variables.py
setup.py

Python version bump made OpenFisca Web API much much slower.
It takes 5 minutes or so (cf discussion on Slack).
This slow startup is mainly due to the introspection data generation and more precisely to the python files parsing.
**similar to #1188**
- In _Variables_:
- `get_introspection_data` no longer have parameters as well as calling functions
I think it is worth sharing my development strategy:
I worked with a country package (France) and started `gunicorn run --config config.py` with
> `run.py`
```python
from openfisca_core.scripts import build_tax_benefit_system
from openfisca_web_api.app import create_app
country_package = 'openfisca_france'
tax_benefit_system = build_tax_benefit_system(
country_package_name = country_package,
extensions = [],
reforms = []
)
application = …
```

Refactor introspection data generation to get a much quicker startup time

---

CHANGELOG.md
openfisca_core/entities/entity.py
openfisca_core/entities/role.py
openfisca_core/entities/typing.py
openfisca_core/taxbenefitsystems/tax_benefit_system.py
openfisca_core/variables/variable.py
openfisca_tasks/test_code.mk
openfisca_web_api/loader/variables.py
setup.cfg
setup.py
tests/core/tax_scales/test_abstract_rate_tax_scale.py
tests/core/tax_scales/test_abstract_tax_scale.py

Document Role

---

CHANGELOG.md
openfisca_core/entities/__init__.py
openfisca_core/entities/entity.py
openfisca_core/entities/group_entity.py
openfisca_core/entities/helpers.py
openfisca_core/entities/role.py
openfisca_core/entities/tests/test_entity.py
openfisca_core/entities/tests/test_group_entity.py
openfisca_core/entities/tests/test_role.py
openfisca_core/entities/typing.py
openfisca_tasks/lint.mk
pyproject.toml
setup.py

Add tests to entities

---

CHANGELOG.md
openfisca_core/tracers/tracing_parameter_node_at_instant.py
setup.py

> As `TracingParameterNodeAtInstant` is a wrapper for `ParameterNodeAtInstant`
> which allows iteration and the use of `contains`, it was not possible
> to use those on a `TracingParameterNodeAtInstant`
- Allows iterations on `TracingParameterNodeAtInstant`
- Allows keyword `contains` on `TracingParameterNodeAtInstant`

Add dunder contains and dunder iter to TracingParameterNodeAtInstant

---

CHANGELOG.md
openfisca_core/taxbenefitsystems/tax_benefit_system.py
setup.py

This follows #1208 that broke backwards compatibility and led to a yanked release.
Tested on Country Template and France.
- Bring back ability to load package metadata as required by Web API from `setup.py`, while maintaining compatibility with more modern `pyproject.toml`.
- Increase resilience to missing metadata.
- Simplify code by grouping exception catching.
- Log warnings when metadata cannot be obtained.

Increase compatibility and resilience of package metadata loading

---

.github/workflows/workflow.yml
CHANGELOG.md
setup.py

- Update documentation deployment trigger to adapt to https://github.com/openfisca/openfisca-doc/pull/308
- - - -
Proof that the deployment is triggered can be found on the [Doc Actions log](https://github.com/openfisca/openfisca-doc/actions/runs/9175096799).
Details of implementation and difficulties can be found on https://github.com/openfisca/openfisca-doc/pull/308#issuecomment-2121712431.
I suggest to wait until https://github.com/openfisca/openfisca-doc/pull/309 is merged to proceed with merging this PR, as it would be the ideal moment to change the `ref` to `main` rather than having an additional patch published later. The review is still relevant to have now thought, considering that the logic itself will not change.
- - - -
If this PR is merged:

Deploy documentation

---

CHANGELOG.md
openfisca_core/entities/__init__.py
openfisca_core/entities/_core_entity.py
openfisca_core/entities/entity.py
openfisca_core/entities/group_entity.py
openfisca_core/entities/helpers.py
openfisca_core/entities/role.py
openfisca_core/entities/types.py
openfisca_core/populations/population.py
openfisca_core/projectors/helpers.py
openfisca_core/projectors/typing.py
openfisca_core/types.py
openfisca_tasks/lint.mk
setup.cfg
setup.py

Depends on #1219
Depended upon by #1146 
- Fix doc & type definitions in the entities module

[3/17] Fix doc & type definitions in the entities module

---

CHANGELOG.md
openfisca_core/data_storage/on_disk_storage.py
openfisca_core/indexed_enums/__init__.py
openfisca_core/indexed_enums/_enum_type.py
openfisca_core/indexed_enums/_type_guards.py
openfisca_core/indexed_enums/enum.py
openfisca_core/indexed_enums/enum_array.py
openfisca_core/indexed_enums/tests/test_enum.py
openfisca_core/indexed_enums/tests/test_enum_array.py
openfisca_core/indexed_enums/types.py
openfisca_core/types.py
openfisca_tasks/test_code.mk
setup.cfg
setup.py
tests/core/tools/test_assert_near.py

Depends on #1272
Fixes #1267
- Introduce `indexed_enums.EnumType`
- Allows for actually fancy indexing `indexed_enums.Enum`
- Fix doctests
- Fix bug in `Enum.encode` when passing a scalar
- Still raises `TypeError` but with an explanation of why it fails
- Fix bug in `Enum.encode` when encoding values not present in the enum
- When encoding values not present in an enum, `Enum.encode` always encoded the first item of it
- Now, it correctly encodes only the values requested that exist in the enum
```python
from openfisca_core import indexed_enums as enum
class TestEnum(enum.Enum):
ONE = "one"
TWO = "two"
TestEnum.encode([2])
```
```python
from openfisca_core import indexed_enums as enum
class TestEnum(enum.Enum):
ONE = "one"
TWO = "two"
TestEnum.encode([2])
TestEnum.encode([0,1,2,5])
```

test(enums): fix enums doctests

---

CHANGELOG.md
openfisca_core/entities/__init__.py
openfisca_core/entities/_core_entity.py
openfisca_core/entities/_description.py
openfisca_core/entities/entity.py
openfisca_core/entities/group_entity.py
openfisca_core/entities/helpers.py
openfisca_core/entities/role.py
setup.cfg
setup.py

Fixes #1254 
Depends on #1253 
Supersedes #1034  
- Make `CoreEntity` public
- Allows for more easily creating customised entities.
- Add missing doctests.

test(entities): fix doctests

---

.conda/openfisca-country-template/recipe.yaml
.conda/openfisca-extension-template/recipe.yaml
CHANGELOG.md
CONTRIBUTING.md
Makefile
README.md
STYLEGUIDE.md
openfisca_core/commons/formulas.py
openfisca_core/entities/_core_entity.py
openfisca_core/parameters/parameter_node_at_instant.py
openfisca_core/parameters/vectorial_parameter_node_at_instant.py
openfisca_core/populations/group_population.py
openfisca_core/projectors/helpers.py
openfisca_core/simulations/simulation.py
openfisca_core/taxbenefitsystems/tax_benefit_system.py
openfisca_tasks/lint.mk
pyproject.toml
setup.py
tests/core/variables/test_variables.py
tests/fixtures/yaml_tests/test_name_filter.yaml
tests/web_api/test_calculate.py
tests/web_api/test_variables.py

- Add check to spot common spelling mistakes

build: add spell check

---

.github/workflows/_test-pip.yaml
CHANGELOG.md
openfisca_core/data_storage/on_disk_storage.py
openfisca_core/indexed_enums/enum.py
openfisca_core/tools/simulation_dumper.py
setup.py
tests/core/test_yaml.py

- Improve the way Enum arrays are loaded and saved in dumps

Improve dump restore

---

CHANGELOG.md
openfisca_core/scripts/openfisca_command.py
openfisca_core/tools/test_runner.py
openfisca_core/tracers/computation_log.py
setup.py

Fixes #1293
See also #1299
- Add `int` default to `max_depth` in `openfisca test`

fix: default maxsize

---

CHANGELOG.md
openfisca_core/indexed_enums/_enum_type.py
openfisca_core/indexed_enums/_utils.py
openfisca_core/indexed_enums/enum.py
openfisca_core/indexed_enums/enum_array.py
setup.py

Fixes  #1306
- Fix enum's module performance issues
- `43.0.0` fixed impending bugs in `indexed_enums` and improved `EnumArray`
performance
- However, `Enun.__eq__` and `Enum.encode` suffered from performance
degradation on large datasets
- This changeset aims at correcting these while keeping the bugfixes provided
by the aforesaid published version
Some of the spectacular performances of `Enum.encode` came from the fact that
it didn't actually work, leaving buggy behaviour unseen (see for example
https://github.com/openfisca/openfisca-france/pull/2357/commits/84e41a5007f8bc23ec74ee3a693bc21e4c20df73).
This PR introduces `O(n)` and `O(1)` use of fancy indexing, vector masking, and
`numpy.searchsorted`, that scales nicely with large datasets (10k+).
However, as we need to validate data at …

perf: fix enum performance

---

CHANGELOG.md
openfisca_core/tracers/computation_log.py
setup.py

Fixes #1310
Depends on #1321
- Fix `computation_log`.

revert: restore line printing in tracer

---

CHANGELOG.md
openfisca_core/taxbenefitsystems/tax_benefit_system.py
setup.py
tests/core/test_tracers.py

Depends on #1321
- Change the copy of the variables in tax_benefit_system.clone() to a deepcopy

fix: deepcopy variables in clone of tax_benefit_system

---

CHANGELOG.md
openfisca_core/commons/__init__.py
openfisca_core/commons/formulas.py
openfisca_core/commons/misc.py
openfisca_core/commons/rates.py
openfisca_core/commons/types.py
openfisca_core/types.py
setup.py

- Move types from `openfisca_core.commons` to `openfisca_core`

refactor: consolidate commons module types

---

CHANGELOG.md
openfisca_core/populations/_core_population.py
openfisca_core/reforms/reform.py
setup.py

Depended upon by https://github.com/openfisca/openfisca-doc/pull/315
- Remove ambiguous documentation references

docs: fix ambiguous doc refs

---

.github/workflows/merge.yaml
.github/workflows/push.yaml
CHANGELOG.md
setup.py
tasks/publish.mk

This PR will close #1287 
OpenFisca-core is working with Python 3.12 since the version 43, but allowed minimal Numpy version, 1.24, do not work with Python 3.12.
So this PR change matrix test to only test Numpy version 1.26.4 with Python 3.12, and 1.24.2 + 1.26.4 for Python 3.9.13.

Update python version to 3.12.3

---

.github/workflows/merge.yaml
CHANGELOG.md
setup.py

The previous build of Core [refuses to upload](https://github.com/openfisca/openfisca-core/actions/runs/14795653690/job/41542588268), the error was:
```
Uploading distributions to https://upload.pypi.org/legacy/
ERROR    InvalidDistribution: Metadata is missing required fields: Name,        
Version.                                                               
Make sure the distribution includes the files where those fields are   
specified, and is using a supported Metadata-Version: 1.0, 1.1, 1.2,   
2.0, 2.1, 2.2, 2.3.  
```
In the METADATA file inside the dist archive we read:
`Metadata-Version: 2.4`
The solution proposed here is to bump the twine version to support Metadata-Version 2.4.
I also add a check of the dist files before trying to upload them.

Bump twine version to >= 6

---

.github/workflows/merge.yaml
.github/workflows/push.yaml
CHANGELOG.md
openfisca_core/reforms/reform.py
setup.py
tests/core/parameter_validation/test_reform_parameter_validation.py

- the modify_my_parameters function should return the ParameterNode, but you're not getting the expected error.  In the modify_parameters method on line 81, there's a bug in the code. It should raise a ValueError, but instead it returns a ValueError. This means the error is created but not actually thrown, so your code continues executing without the expected error.
- Will close #1331

Fix `return` instead of `raise`.
