- openfisca_core/periods.py
Add `last year` reference period
Add `size_in_month` property
> Small additions to period

- openfisca_core/columns.py
- openfisca_core/formulas.py
- openfisca_core/reforms.py
- openfisca_core/scripts/measure_performances.py
- openfisca_core/tests/dummy_country.py
- openfisca_core/tests/test_countries.py
- openfisca_core/tests/test_cycles.py
- openfisca_core/tests/test_reforms.py
> Simplify variables declaration (without decorator)

- openfisca_core/reforms.py
These classes are needed to use these column types in reforms
> Add useful classes to Reform

- CHANGELOG.md
- openfisca_core/simulations.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/tests/test_countries.py
- setup.py
Replaces #394
Explicit the error when a variable is not found
@benjello can you please check that this behaviour suits your need ?
> Detect absent variables

- CHANGELOG.md
- openfisca_core/columns.py
- openfisca_core/formulas.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/variables.py
- setup.py
This allows to enhance data served by the web API which itself feeds the Legislation Explorer.
> Update introspection data

- CHANGELOG.md
- openfisca_core/base_functions.py
- openfisca_core/tests/test_extra_params.py
- setup.py
Should fix https://github.com/openfisca/openfisca-france/issues/523
> Adapt base_functions to extra params

- CHANGELOG.md
- openfisca_core/columns.py
- openfisca_core/formulas.py
- openfisca_core/variables.py
- setup.py
See https://github.com/openfisca/openfisca-france/issues/543
> Fix cerfa field validation

- CHANGELOG.md
- openfisca_core/columns.py
- setup.py
Comes with https://github.com/openfisca/openfisca-france/pull/594/
> Enforce DateCol.default to be a date

- CHANGELOG.md
- openfisca_core/legislations.py
- openfisca_core/legislationsxml.py
- setup.py
Needed by baremes-ipp branch in openfisca-france
> Add conflicts and origin fields to xml params

- CHANGELOG.md
- openfisca_core/reforms.py
- openfisca_core/tests/test_reforms.py
- setup.py
Needed by openfisca/openfisca-france#566
> Fix update_legislation in reforms

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/scenarios.py
- openfisca_core/tests/test_scenarios.py
- setup.py
Should fix some of the errors in https://github.com/openfisca/openfisca-france-data/issues/121#event-875244866
> Enable simulation initialization with only legacy roles

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/formulas.py
- setup.py
I'm also removing the beta flag, as most openfisca packages have successfully migrated.
> Add extra params to new syntax

- CHANGELOG.md
- doc/README.md
- doc/requirements.txt
- doc/source/_static/css/custom.css
- doc/source/conf.py
- doc/source/index.rst
- doc/source/openfisca-run-test.rst
- doc/source/test_runner.rst
- setup.py
Available on http://openfisca.readthedocs.io/.
> Add reference documentation

- CHANGELOG.md
- openfisca_core/decompositions.py
- openfisca_core/reforms.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/tests/test_opt_out_cache.py
- setup.py
> Refactor decompositions

- CHANGELOG.md
- doc/requirements.txt
- doc/source/index.rst
- doc/source/tax-benefit-system.rst
- openfisca_core/taxbenefitsystems.py
- setup.py
See http://openfisca.readthedocs.io/en/doc/tax-benefit-system.html
> Add TaxBenefitSystem doc to the reference doc

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/formulas.py
- openfisca_core/holders.py
- openfisca_core/simulations.py
- openfisca_core/tests/test_countries.py
- openfisca_core/tests/test_cycles.py
- openfisca_core/tests/test_entities.py
- openfisca_core/tests/test_extra_params.py
- openfisca_core/tests/test_formulas.py
- openfisca_core/tests/test_opt_out_cache.py
- openfisca_core/tests/test_reforms.py
- setup.py
> Make it mandatory to specify periods in variable calls

- CHANGELOG.md
- setup.py
Connected to openfisca/openfisca-parsers#27
Context: @davidbgk suggested to introduce this extra_require in [his comment](https://github.com/openfisca/openfisca-parsers/pull/27#issuecomment-281358329)
> Add extra require for parsers

- CHANGELOG.md
- openfisca_core/entities.py
- setup.py
Precedes https://github.com/openfisca/openfisca-web-api/pull/73
> Make Entity provide its own JSON representation

- CHANGELOG.md
- openfisca_core/json_to_test_case.py
- openfisca_core/scenarios.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/tests/test_json_to_test_case.py
- setup.py
> Improve errors for non-existing variables

- CONTRIBUTING.md
- README.md
Connected to openfisca/openfisca-core#471
> Remove "/en" from URLs

- CHANGELOG.md
- openfisca_core/formulas.py
- openfisca_core/periods.py
- setup.py
Connected to https://github.com/openfisca/openfisca-web-api/issues/110
Precedes https://github.com/openfisca/openfisca-web-api/pull/111
> Fix typos in error messages

- CHANGELOG.md
- openfisca_core/base_functions.py
- openfisca_core/columns.py
- openfisca_core/formulas.py
- openfisca_core/holders.py
- setup.py
- tests/test_reforms.py
Alternative implementation to #433 
@benjello tell me if it does the job for you
> Do not cache values for neutralize columns

- CHANGELOG.md
- openfisca_core/formulas.py
- openfisca_core/holders.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/variables.py
- setup.py
- tests/test_countries.py
- tests/test_entities.py
Connected to openfisca/openfisca-web-api#125
> Improve country packages and formulas metadata

- CHANGELOG.md
- openfisca_core/legislationsxml.py
- setup.py
Connected to openfisca/openfisca-core#437
Fixes regression introduced by #488
> Keep description for parameters

- CHANGELOG.md
- openfisca_core/formulas.py
- setup.py
> Handle variables with several references

- CHANGELOG.md
- openfisca_core/taxbenefitsystems.py
- openfisca_core/variables.py
- setup.py
Connected to openfisca/legislation-explorer#82
> Make location computation more robust

- CHANGELOG.md
- LICENSE.AGPL.txt
- openfisca_core/decompositionsxml.py
- openfisca_core/formulas.py
- openfisca_core/legislations.py
- openfisca_core/legislationsxml.py
- setup.py
> Keep definition period when updating a variable

- CHANGELOG.md
- openfisca_core/entities.py
- setup.py
- tests/core/test_countries.py
> Improve the error when the period argument is forgotten

- CHANGELOG.md
- check-version-bump.sh
- openfisca_core/legislation.xsd
- openfisca_core/legislations.py
- openfisca_core/legislationsxml.py
- openfisca_core/taxbenefitsystems.py
- setup.py
- tests/core/parameter_validation/malformed.xml
- tests/core/parameter_validation/test_parameter_validation.py
- tests/core/parameter_validation/unknown_node.xml
- tests/core/parameter_validation/wrong_bareme.xml
- tests/core/parameter_validation/wrong_value.xml
Connected to #474 
Improve error message during parameters validation, using lxml with a XML schema. No breaking change for users.
> Raise nicer errors when legislation is invalid

- MANIFEST.in
- circle.yml
The XSD file introduced by #505 was not packaged. Caused production collapse 😱
> Fix packaging

- doc/requirements.txt
- doc/source/conf.py
- doc/source/index.rst
- doc/source/parameter.rst
- doc/source/parameters.rst
- doc/source/variable.rst
- doc/source/variables.rst
Connected to openfisca/openfisca-web-api#129
> Document preview API routes

- CHANGELOG.md
- MANIFEST.in
- openfisca_web_api_preview/app.py
- openfisca_web_api_preview/loader/__init__.py
- openfisca_web_api_preview/openAPI.yml
- setup.py
- tests/web_api/test_openAPI.py
Connected to #514.
Serve the OpenAPI specification under the API route `/swagger/`
> Add an OpenAPI route

- CHANGELOG.md
- openfisca_core/legislation.xsd
- openfisca_core/legislations.py
- openfisca_core/legislationsxml.py
- setup.py
- tests/core/parameter_validation/free_text.xml
- tests/core/parameter_validation/test_parameter_validation.py
Connected to https://github.com/openfisca/openfisca-france/issues/766
> Disallow comments in XML parameters files

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/holders.py
- openfisca_core/simulations.py
- setup.py
- tests/core/test_simulations.py
- Fix `simulation.clone` and `entity.clone` methods
> Fix simulation.clone and entity.clone

- CHANGELOG.md
- openfisca_core/formulas.py
- openfisca_core/simulations.py
- setup.py
Connected to openfisca/openfisca-web-api#134
> Fix `formula.graph_parameters`,  `formula.to_json` and  `simulation.graph`

- CHANGELOG.md
- openfisca_web_api_preview/openAPI.yml
- setup.py
Depends on #539
Connected to openfisca/legislation-explorer#100
> Rewrite /calculate example for france

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/simulations.py
- openfisca_web_api_preview/loader/spec.py
- setup.py
- tests/core/test_entities.py
- tests/core/test_simulations.py
- tests/web_api/test_calculate.py
Connected to openfisca/demonstrator#3
Connected to #532
A few problems emerged when using the new route `/calculate` with `openfisca-france`.
> Improve preview  api

- CHANGELOG.md
- openfisca_core/columns.py
- openfisca_core/formulas.py
- openfisca_core/reforms.py
- openfisca_core/scenarios.py
- openfisca_core/simulations.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/variables.py
- openfisca_web_api_preview/loader/variables.py
- setup.py
- tests/core/test_reforms.py
> Url rename

- CHANGELOG.md
Improve changelog readability
This change doesn't bump the version number as it is a pure metadata change.
> Unify title levels

- circle.yml
- deploy-if-version-bump.sh
Connected to #513 
When there is a new commit on the master branch, if the version number has not been changed, the deployment will not be triggered.
> Check version number change before deployment

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- openfisca_core/entities.py
- openfisca_core/formulas.py
- openfisca_core/parameters.py
- openfisca_core/periods.py
- openfisca_web_api_preview/openAPI.yml
- setup.py
- tests/web_api/test_variables.py
Connected to openfisca/openfisca-doc#89
Depends on https://github.com/openfisca/country-template/pull/21
> Reference the new address of the documentation

- CHANGELOG.md
- openfisca_core/scripts/migrations/v16_2_to_v17/legislation.xsd
- openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml.py
- openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml_country_template.py
- openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml_extension_template.py
- setup.py
> Keep references when migrating XML params to YAML

- CHANGELOG.md
- openfisca_web_api_preview/app.py
- setup.py
Connected to openfisca/openfisca-france#821
🎉
> Track the real visitor IP

- CHANGELOG.md
- setup.py
> Fix version number

- CHANGELOG.md
- circle.yml
- doc/source/enum_array.rst
- doc/source/index.rst
- openfisca_core/base_functions.py
- openfisca_core/columns.py
- openfisca_core/entities.py
- openfisca_core/formulas.py
- openfisca_core/holders.py
- openfisca_core/indexed_enums.py
- openfisca_core/model_api.py
- openfisca_core/parameters.py
- openfisca_core/scenarios.py
- openfisca_core/tools/__init__.py
- openfisca_core/tracers.py
- openfisca_core/variables.py
- openfisca_web_api_preview/app.py
- openfisca_web_api_preview/loader/spec.py
- openfisca_web_api_preview/loader/variables.py
- setup.py
- tests/core/test_holders.py
- tests/web_api/basic_case/test_calculate.py
Connected to openfisca/openfisca-france#831
Improve performance of changes introduced in `21.0`.
For changelog clarity, I recommand unpublishing the intertermediate step `21.0`, as no one is using it.
> Improve Enums performance

- CHANGELOG.md
- openfisca_core/variables.py
- openfisca_web_api_preview/app.py
- openfisca_web_api_preview/loader/variables.py
- setup.py
- tests/web_api/basic_case/test_parameters.py
- tests/web_api/basic_case/test_variables.py
Fixes openfisca/openfisca-france#891
- Fixes encoding for API `/parameter` and `/variable` endpoints
> Decode API /parameter and /variable

- CHANGELOG.md
- openfisca_web_api_preview/app.py
- setup.py
Setting values in a complex object seems very slow using a proxy object improves performance
- Make API faster
> Improve API response time

- CHANGELOG.md
- setup.py
- Adapt to version `2.1.0` of Country-Template and version `1.1.3` of extension template.
> Adapt to template and extension current versions

- CHANGELOG.md
- openfisca_web_api_preview/openAPI.yml
- setup.py
- tests/web_api/basic_case/test_spec.py
- /spec endpoint is described in the swagger documentation
> Add swagger documentation for /spec endpoint

- CHANGELOG.md
- openfisca_core/tracers.py
- openfisca_web_api_preview/openAPI.yml
- setup.py
Depends on #598.
_Attention: this PR is opened towards `update-taxipp-v20` to make the diff clearer. Once #598 is merged, the target branch must be changed to master_
This PR is the straight continuation of #598, and could be included in it. However, #598 is more urgent and should not be delayed to integrate this.
- Improve `Tracer`:
- Make aggregation more efficient
- Introduce [`tracer.print_trace`](http://openfisca.readthedocs.io/en/latest/tracer.html#openfisca_core.tracers.Tracer.print_trace)
> Improve tracer

- CHANGELOG.md
- doc/source/openfisca_serve.rst
- setup.py
Connected to #593 
Brings #593 content to openfisca organisation
And adds minor changes: fixup (missing tick) + bump version
> Update openfisca serve rst documentation

- CHANGELOG.md
- openfisca_core/parameters.py
- openfisca_core/tools/__init__.py
- setup.py
Connected to #526 and #613.
This is a fix. See changelog.
> Update dependency on numpy

- CHANGELOG.md
- openfisca_core/indexed_enums.py
- setup.py
- tests/web_api/basic_case/test_calculate.py
- tests/web_api/basic_case/test_variables.py
- Bump country-template version to >=3.0.0, <4.0.0
- Update tests
> Bump country-template version to >=3.0.0, <4.0.0

- CHANGELOG.md
- setup.py
- tests/web_api/basic_case/test_variables.py
* Failing test at `tests/web_api/basic_case/test_variables.py:146`
- Changed `http` to `https`
> Fix test_variables.py failing test

- CHANGELOG.md
- openfisca_web_api_preview/app.py
- setup.py
Requires openfisca/tracker/pull/6
Connected to #594 
- Send reference to the country-package version to the tracker so it will appear in the tracking statistics.
> Send reference to the country-package version to the tracker

- CHANGELOG.md
- openfisca_core/parameters.py
- openfisca_core/tools/test_runner.py
- setup.py
Fixes spelling of English word in warning messages.
> corrected spelling of "environment"

- CHANGELOG.md
- openfisca_web_api/app.py
- openfisca_web_api/loader/__init__.py
- openfisca_web_api/loader/parameters.py
- openfisca_web_api/loader/variables.py
- setup.py
- tests/web_api/test_parameters.py
- tests/web_api/test_variables.py
fixes #512 
- Enhance navigation within the Openfisca Web API.
- Provides a direct link to individual parameters and variables from the /parameters and /variables routes respectively.
> Improve Web API navigability

- CHANGELOG.md
- setup.cfg
- setup.py
- tests/web_api/test_entities.py
Ignore W503 to enforce Knuth's style.
> Correct style ignore: W503 rather than W504

- CHANGELOG.md
- openfisca_core/variables.py
- setup.py
- tests/core/test_variables.py
- tests/web_api/test_trace.py
The recent fix bug has a much more impact than expected. 
Reverting to take more time to think about it.
> Revert casting of string variables to unicode

- CHANGELOG.md
- openfisca_core/parameters.py
- openfisca_core/periods.py
- openfisca_core/scripts/measure_performances_fancy_indexing.py
- setup.py
- Apply PEP8 W504: break line before binary operator.
> Apply PEP8 W504 (Knuth's Style)

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/rates.py
- openfisca_core/tools/simulation_dumper.py
- setup.py
- Fix average_rate computation when division by zero are present
- Fix entity.count restoration for a simulation dump
> Minor fixes

- CHANGELOG.md
- openfisca_core/parameters.py
- openfisca_core/simulations.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/taxscales.py
- openfisca_core/tracers.py
- openfisca_web_api/openAPI.yml
- setup.py
- tests/core/test_simulations.py
- tests/core/test_tracer.py
Fixes #701 
- Add parameters in `/trace` web api endpoint
> Add parameters in trace

- CHANGELOG.md
- openfisca_core/parameters.py
- openfisca_web_api/loader/parameters.py
- setup.py
- tests/core/test_parameters.py
- tests/web_api/loader/test_parameters.py
- Introduce `ParameterNode.get_descendants`
- This method returns a generator containing all the parameters and nodes recursively contained in the `ParameterNode`
(I need this helper to parse the IPP parameters, and as it's not the first time we need this, I think a method would is useful)
> Introduce ParameterNode.get_descendants

- CHANGELOG.md
- openfisca_core/parameters.py
- setup.py
- tests/core/test_tax_scales.py
> Fix amount scale parameters' access

- CHANGELOG.md
- openfisca_core/__init__.py
- openfisca_core/scripts/__init__.py
- openfisca_core/tools/test_runner.py
- setup.py
- Allow OpenFisca-Core users to define their own level of log)
> Don't impose log config

- CHANGELOG.md
- openfisca_web_api/scripts/serve.py
- setup.py
> Add default timeout

- CHANGELOG.md
- openfisca_core/simulations.py
- setup.py
Fix #740 
@maukoquiroga @fpagnoux : i also tried to make the doctest work for simulation
> Simulation delete arrays

- CHANGELOG.md
- openfisca_core/model_api.py
- openfisca_core/periods.py
- openfisca_core/simulations.py
- openfisca_core/variables.py
- setup.py
- tests/core/test_periods.py
> Add support for DAY periods

- CHANGELOG.md
- openfisca_core/holders.py
- setup.py
- tests/core/test_holders.py
> Optimize set_input_dispatch_by_period

- .circleci/config.yml
- CHANGELOG.md
- setup.cfg
- setup.py
- Add test coverage to put a nice badge in README.me 😃 
- Config `coverage.py` plugin for `pytest`
- Submit code coverage in CircleCI
> Add test coverage

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_core/simulation_builder.py
- openfisca_core/simulations.py
- openfisca_core/taxbenefitsystems.py
- setup.py
- tests/core/test_simulation_builder.py
Connected to openfisca/openfisca-doc#168
- Introduce tabular oriented simulation building
- Allow to create a simulation step by step:
1. Create entities with `SimulationBuilder.create_entities(...)`
2. Declare your population 
with `SimulationBuilder.declare_person_entity(...)` and `SimulationBuilder.declare_entity(...)`
3. Link between persons in population definition with `SimulationBuilder.join_with_persons(...)`
4. Build a simulation with `SimulationBuilder.build(...)`
5. Set variable values with the already existing `Simulation.set_input(...)` method
---
For this `data_persons.csv`:
```csv
person_id,household_id,role_in_household,salary,age
1,a,first_parent,2694,40
2,a,second_parent,2720,43
3,b,first_parent,3865,45
4,b,child,1300,23
5,c,child,0,12
6,c,child,0,14 …
```
> Build simulation with tabular inputs

- CHANGELOG.md
- openfisca_core/simulation_builder.py
- setup.py
- tests/core/yaml_tests/test_success.yaml
- Fixes bug introduced in 27.0.0
> Fix end date comparison

- CHANGELOG.md
- openfisca_core/scripts/find_placeholders.py
- openfisca_core/scripts/measure_numpy_condition_notations.py
- openfisca_core/scripts/measure_performances.py
- openfisca_core/scripts/measure_performances_fancy_indexing.py
- openfisca_core/scripts/migrations/v16_2_to_v17/xml_to_yaml.py
- openfisca_core/scripts/migrations/v24_to_25.py
- openfisca_core/simulations.py
- openfisca_core/tools/test_runner.py
- openfisca_core/tracers.py
- setup.py
😓 Previous PR introduced a couple "print" statements…
> Remove stray print statements

- CHANGELOG.md
- openfisca_core/indexed_enums.py
- openfisca_web_api/handlers.py
- setup.py
- tests/core/test_tracer.py
- tests/web_api/test_trace.py
- Display symbolic values of Enums in /trace and print_computation_log
Fixes #822
> Display symbolic values of Enums in /trace and print_computation_log

- CHANGELOG.md
- openfisca_core/simulation_builder.py
- openfisca_core/tools/test_runner.py
- setup.py
- tests/web_api/test_calculate.py
> Improve error messages for entity role issues

- CHANGELOG.md
- README.md
- openfisca_core/errors.py
- openfisca_core/holders.py
- openfisca_core/periods.py
- openfisca_core/scripts/measure_numpy_condition_notations.py
- openfisca_core/scripts/run_test.py
- openfisca_core/simulations.py
- openfisca_core/taxbenefitsystems.py
- openfisca_core/tools/test_runner.py
- openfisca_core/tracers.py
- openfisca_core/variables.py
- setup.cfg
- setup.py
- tests/core/parameters_fancy_indexing/test_fancy_indexing.py
- tests/core/test_extensions.py
- tests/core/test_formula_helpers.py
- tests/core/test_parameters.py
- tests/core/test_variables.py
- tests/core/test_yaml.py
- tests/core/tools/test_runner/test_yaml_runner.py
- tests/core/yaml_tests/test_name_filter.yaml
- tests/web_api/test_entities.py
- tests/web_api/test_parameters.py
- tests/web_api/test_spec.py
- tests/web_api/test_trace.py
- tests/web_api/test_variables.py
Depends on  #865 
_PR temporarily opened against branch `error-roles` for diff readability_
Use PyTest instead of nose in `openfisca test`
> Use Pytest in the test runner

- CHANGELOG.md
- openfisca_core/tracers.py
- setup.py
- tests/core/test_tracer.py
- Avoid column-wrapping array values in debug strings
Fixes #869
> Avoid column-wrapping array values in debug strings

- CHANGELOG.md
- openfisca_core/data_storage.py
- openfisca_core/populations.py
- openfisca_core/simulations.py
- openfisca_core/tracers.py
- setup.py
Extracted from #871 
Remove remains of extra parameters
> Cleanup references to extra params

- CHANGELOG.md
- openfisca_core/entities.py
- openfisca_web_api/openAPI.yml
- setup.py
- Update links to the doc in the API
> Update doc links in API

- CHANGELOG.md
- openfisca_core/scripts/assets/index.html
- openfisca_core/tracers.py
- setup.py
- tests/core/test_tracers.py
- tests/core/tools/test_runner/test_yaml_runner.py
I've been using the new performance graph, and found that the following changes made my life easier. See details in comments.
> Improve performance graph

- CHANGELOG.md
- openfisca_core/parameters.py
- setup.py
- tests/core/parameter_validation/test_parameter_clone.py
Fix Parameters.clone() to yield true clones
> Fix parameter-clone

- CHANGELOG.md
- openfisca_core/taxscales.py
- setup.py
- Improve `taxscales.py` documentation
- Details:
- Specify the types of the arguments
- Follow the same style as other parts of the documentation
> Improve taxscales.py documentation

- CHANGELOG.md
- openfisca_core/indexed_enums.py
- setup.py
- Improve `indexed_enums.py` documentation.
- Reduce line length.
- Fix code examples.
- Fix indentation.
> Improve indexed_enums.py documentation

- CHANGELOG.md
- openfisca_core/indexed_enums.py
- setup.py
- Improve `indexed_enums.py` code style.
- Remove useless encoding declaration.
- Use more explicit imports.
- Improve indentation.
- Use f-style string interpolation.
> Improve indexed_enums.py code style

- CHANGELOG.md
- openfisca_core/simulation_builder.py
- setup.py
- tests/core/test_axes.py
- Fix a bug when using axes with an integer year period 
- Always index periods in the inpt_buffer by their string representation
> Complete axis test

- CHANGELOG.md
- setup.cfg
- setup.py
- Merge `flake8` and `pep8` configs as they're redundant.
> Cleanup setup.cfg file

- CHANGELOG.md
- openfisca_core/parameters.py
- setup.py
- Improve error message when laoding parameters file to detect the problematic file
> Increase verbosity

- openfisca_web_api/handlers.py
Refactor dependencies function
> Refactor dependencies function

- tests/web_api/test_parameters.py
> Adjust expected text in api/parameter/benefits route test

- .github/workflows/workflow.yml
- CHANGELOG.md
- setup.py
- Add `pull-request` as a trigger to GitHub Actions workflow.
> Add pull request as CI workflow trigger

- CHANGELOG.md
- openfisca_core/parameters/parameter.py
- openfisca_core/parameters/parameter_at_instant.py
- openfisca_core/parameters/parameter_node.py
- openfisca_core/reforms/reform.py
- openfisca_core/taxbenefitsystems/tax_benefit_system.py
- openfisca_core/tools/test_runner.py
- openfisca_core/variables/variable.py
- setup.py
https://github.com/openfisca/openfisca-doc/pull/264
@MattiSG
> Fix docstrings

- CHANGELOG.md
- openfisca_core/scripts/openfisca_command.py
- openfisca_core/scripts/run_test.py
- openfisca_core/tools/test_runner.py
- openfisca_core/tracers/computation_log.py
- openfisca_core/tracers/full_tracer.py
- setup.py
- tests/core/test_tracers.py
- Introduce a maximal depth for compuation logs
- Allows for limiting the depth of the computation log chain
> Add a depth-max for test logs

- CHANGELOG.md
- openfisca_core/holders/__init__.py
- openfisca_core/holders/holder.py
- openfisca_core/holders/memory_usage.py
- openfisca_core/populations/population.py
- openfisca_core/types/_domain.py
- openfisca_tasks/install.mk
- openfisca_tasks/test_code.mk
- setup.cfg
- setup.py
> Fix Holder's doctests

- CHANGELOG.md
- openfisca_core/scripts/measure_numpy_condition_notations.py
- openfisca_core/scripts/measure_performances.py
- openfisca_core/scripts/measure_performances_fancy_indexing.py
- openfisca_core/scripts/remove_fuzzy.py
- openfisca_core/scripts/simulation_generator.py
- openfisca_core/tools/__init__.py
- openfisca_core/tools/simulation_dumper.py
- setup.py
- tests/core/parameters_fancy_indexing/test_fancy_indexing.py
- tests/core/test_projectors.py
- tests/core/test_tracers.py
- tests/core/tools/test_assert_near.py
- tests/core/tools/test_runner/test_yaml_runner.py
- tests/core/variables/test_annualize.py
Part of #673 
- Always import numpy
> Always import numpy

- CHANGELOG.md
- openfisca_core/entities/role.py
- setup.py
> Add __hash__ for Role

- CHANGELOG.md
- setup.py
fix: https://github.com/openfisca/openfisca-core/issues/1198
- Bump Gunicorn version
> chore: bump gunicorn version to `~21`

- openfisca_core/parameters/__init__.py
- openfisca_core/parameters/parameter_node_at_instant.py
- openfisca_core/parameters/vectorial_asof_date_parameter_node_at_instant.py
- openfisca_core/tools/test_runner.py
- tests/core/parameters_date_indexing/aad_rg.yaml
- tests/core/parameters_date_indexing/full_rate_age.yaml
- tests/core/parameters_date_indexing/full_rate_required_duration.yml
- tests/core/parameters_date_indexing/test_date_indexing.py
- tests/core/parameters_date_indexing/trimtp_rg.yml
- tests/core/parameters_fancy_indexing/coefficient_de_minoration.yaml
- In _some module_:
- Remove…
- Introduce `some_function()`
- Allows for…
- Deprecate `some_function`.
- The functionality is now provided by…
- Rename `private_function`.
> Draft: Pension rebased

- setup.py
- Bump twine version to allow deployment.
> Bump twine version to allow deployment

- CHANGELOG.md
- openfisca_core/parameters/__init__.py
- openfisca_core/parameters/parameter_node_at_instant.py
- openfisca_core/parameters/vectorial_asof_date_parameter_node_at_instant.py
- openfisca_tasks/lint.mk
- setup.py
- tests/core/parameters_date_indexing/test_date_indexing.py
- Fix styles by applying `black`.
- Add a `black` dry-run check to `make lint`
> Fix black styles

- CHANGELOG.md
- openfisca_core/commons/formulas.py
- openfisca_core/commons/misc.py
- openfisca_core/commons/rates.py
- openfisca_core/entities/_core_entity.py
- openfisca_core/populations/population.py
- openfisca_core/simulations/simulation.py
- openfisca_core/simulations/typing.py
- openfisca_core/taxbenefitsystems/tax_benefit_system.py
- openfisca_core/taxscales/amount_tax_scale_like.py
- openfisca_core/taxscales/rate_tax_scale_like.py
- openfisca_core/taxscales/tax_scale_like.py
- openfisca_core/tools/test_runner.py
- openfisca_core/types/_domain.py
- openfisca_core/variables/variable.py
- openfisca_tasks/lint.mk
- setup.cfg
- setup.py
- tests/core/parameters_date_indexing/test_date_indexing.py
Depends on #1216 
- Fix styles by applying `isort`.
- Add a `isort` dry-run check to `make lint`
> Fix isort styles

- CHANGELOG.md
- openfisca_core/commons/__init__.py
- openfisca_core/commons/formulas.py
- openfisca_core/commons/misc.py
- openfisca_core/commons/rates.py
- openfisca_core/entities/_core_entity.py
- openfisca_core/entities/_description.py
- openfisca_core/entities/entity.py
- openfisca_core/entities/group_entity.py
- openfisca_core/entities/helpers.py
- openfisca_core/entities/role.py
- openfisca_core/entities/tests/test_role.py
- openfisca_core/periods/helpers.py
- openfisca_core/simulations/simulation_builder.py
- setup.cfg
- setup.py
Fixes #1252 
- Fix documentation of `entities`
> docs(entities): fix docs

- CHANGELOG.md
- openfisca_core/commons/formulas.py
- setup.py
> docs(commons): fix bad indent

- .github/workflows/merge.yaml
- openfisca_tasks/publish.mk
Related to #1203
- Fix the script to publish to PyPi
> ci: fix deploy to PyPi

- CHANGELOG.md
- openfisca_core/data_storage/in_memory_storage.py
- openfisca_core/data_storage/on_disk_storage.py
- openfisca_tasks/test_code.mk
- setup.py
Fixes #1249
- Fix doctests of `data_storage` module
> test(storage): fix data_storage doctest

- CHANGELOG.md
- openfisca_core/data_storage/in_memory_storage.py
- openfisca_core/data_storage/on_disk_storage.py
- openfisca_tasks/lint.mk
- setup.py
Fixes #1262
Depends on #1261
- Fix docs of the `data_storage` module
> docs(storage): fix data_storage docs

- .conda/openfisca-core/meta.yaml
- .github/workflows/_before-conda.yaml
- .github/workflows/merge.yaml
- CHANGELOG.md
- openfisca_core/data_storage/__init__.py
- openfisca_core/data_storage/in_memory_storage.py
- openfisca_core/data_storage/on_disk_storage.py
- openfisca_core/data_storage/types.py
- openfisca_core/indexed_enums/enum.py
- openfisca_core/indexed_enums/enum_array.py
- openfisca_core/indexed_enums/types.py
- openfisca_core/types.py
- openfisca_tasks/lint.mk
- setup.py
Fixes #1235 
- Add typing to `data_storage` module
> docs(storage): fix data_storage types

- CHANGELOG.md
- openfisca_core/populations/_errors.py
- openfisca_core/populations/types.py
- openfisca_core/tracers/__init__.py
- openfisca_core/tracers/computation_log.py
- openfisca_core/tracers/flat_trace.py
- openfisca_core/tracers/full_tracer.py
- openfisca_core/tracers/simple_tracer.py
- openfisca_core/tracers/trace_node.py
- openfisca_core/tracers/types.py
- openfisca_core/types.py
- setup.py
Depends on #1279 
Part of #1245
- Add types to common tracers (`SimpleTracer`, `FlatTracer`, etc.)
> docs: add types to tracers (1/3)

- .conda/openfisca-extension-template/recipe.yaml
- .github/workflows/_test-pip.yaml
- CHANGELOG.md
- openfisca_tasks/test_code.mk
- setup.py
- tests/core/test_yaml.py
Fixes #1291
- Use new `extension-template` tests' path
> fix: extension-template tests

- .conda/openfisca-country-template/recipe.yaml
- .conda/openfisca-extension-template/recipe.yaml
- CHANGELOG.md
- setup.py
- tests/core/test_axes.py
- tests/core/test_dump_restore.py
- tests/core/test_entities.py
- tests/core/test_holders.py
- tests/core/test_reforms.py
- tests/core/test_simulation_builder.py
- tests/core/test_simulations.py
- tests/core/variables/test_variables.py
- tests/fixtures/entities.py
- tests/fixtures/yaml_tests/test_success.yml
- tests/fixtures/yaml_tests/test_with_anchors.yaml
- tests/fixtures/yaml_tests/test_with_extension.yaml
- tests/web_api/test_calculate.py
- tests/web_api/test_entities.py
- tests/web_api/test_spec.py
- tests/web_api/test_trace.py
- tests/web_api/test_variables.py
Depends on https://github.com/openfisca/extension-template/pull/65
- Adapt tests to `country-template` 8.0.0.
> test: adapt to country-template v8
